import { formatDate, formatDateTime, formatDateTimeSeconds, formatDateCustom, parseDate, getCurrentDate, subtractDays, toISODate, addDays } from '../../lib/date-utils.ts';
import type { Employee } from './types.ts';
import { asSystemId, asBusinessId } from '../../lib/id-types.ts';

export const data: Employee[] = [
  {
    systemId: asSystemId(asSystemId('EMP000001')),
    id: asBusinessId('NV000001'),
    fullName: 'Nguyễn Văn A',
    workEmail: 'nva@example.com',
    personalEmail: 'nva.personal@gmail.com',
    phone: '0901234567',
    gender: 'Nam',
    dob: '1990-01-01',
    permanentAddress: '123 ABC, Quận 1, TP.HCM',
    jobTitle: 'Nhân viên',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2020-01-01',
    baseSalary: 10000000,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 0,
    role: 'Admin',
    password: 'admin123',
  },
  {
    systemId: asSystemId(asSystemId('EMP000002')),
    id: asBusinessId('NV000002'),
    fullName: 'Trần Thị B',
    workEmail: 'ttb@example.com',
    personalEmail: 'ttb.personal@gmail.com',
    phone: '0912345678',
    gender: 'Nữ',
    dob: '1992-02-02',
    permanentAddress: '456 XYZ, Quận 2, TP.HCM',
    jobTitle: 'Trưởng phòng',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2019-01-01',
    baseSalary: 15000000,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 5,
    role: 'Manager',
    password: 'manager123',
  },
  {
    systemId: asSystemId(asSystemId('EMP000003')),
    id: asBusinessId('NV000003'),
    fullName: 'Lê Văn C',
    workEmail: 'lvc@example.com',
    personalEmail: 'lvc.personal@gmail.com',
    phone: '0923456789',
    gender: 'Nam',
    dob: '1995-03-03',
    permanentAddress: '789 DEF, Quận 3, TP.HCM',
    jobTitle: 'Nhân viên',
    department: 'Kỹ thuật',
    branchSystemId: asSystemId('CN000002'),
    hireDate: '2021-01-01',
    baseSalary: 12000000,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 2,
    role: 'Warehouse',
    password: 'warehouse123',
  },
  {
    systemId: asSystemId(asSystemId('EMP000004')),
    id: asBusinessId('NV000004'),
    fullName: 'Võ Thị F',
    workEmail: 'vtf@example.com',
    personalEmail: 'vtf.personal@gmail.com',
    phone: '0934567890',
    gender: 'Nữ',
    dob: '1993-04-04',
    permanentAddress: '321 GHI, Quận 7, TP.HCM',
    jobTitle: 'Nhân viên',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2020-06-01',
    baseSalary: 11000000,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 3,
    role: 'Sales',
    password: 'sales123',
  },
];
