import { formatDate, formatDateTime, formatDateTimeSeconds, formatDateCustom, parseDate, getCurrentDate, subtractDays, toISODate, addDays } from '../../lib/date-utils';
import type { Employee, EmployeeAddress } from '@/lib/types/prisma-extended';
import { asSystemId, asBusinessId } from '../../lib/id-types';

/**
 * Helper functions to create EmployeeAddress
 * - 2-cấp: Tỉnh/TP → Phường/Xã (bỏ Quận/Huyện)
 * - 3-cấp: Tỉnh/TP → Quận/Huyện → Phường/Xã (đầy đủ)
 */
const createAddress2Level = (
  street: string,
  ward: string,
  province: string,
  provinceId: string = '79',
  wardId: string = ''
): EmployeeAddress => ({
  street,
  province,
  provinceId,
  district: '',      // 2-cấp không có district
  districtId: 0,
  ward,
  wardId,
  inputLevel: '2-level',
});

const createAddress3Level = (
  street: string,
  district: string,
  ward: string,
  province: string,
  provinceId: string = '79',
  districtId: number = 0,
  wardId: string = ''
): EmployeeAddress => ({
  street,
  province,
  provinceId,
  district,
  districtId,
  ward,
  wardId,
  inputLevel: '3-level',
});

const SEED_AUTHOR = asSystemId('EMP000001');
const buildAuditFields = (createdAt: string, createdBy = SEED_AUTHOR) => ({
  createdAt,
  updatedAt: createdAt,
  createdBy,
  updatedBy: createdBy,
});

export const data: Employee[] = [
  {
    systemId: asSystemId(asSystemId('EMP000001')),
    id: asBusinessId('1'),
    fullName: 'Nguyễn Văn A',
    workEmail: 'nva@example.com',
    personalEmail: 'nva.personal@gmail.com',
    phone: '0901234567',
    gender: 'Nam',
    dob: '1990-01-01',
    permanentAddress: createAddress2Level('123 ABC', 'Phường Bến Nghé', 'TP.HCM', '79'),
    temporaryAddress: null,
    jobTitle: 'Giám đốc',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2020-01-01',
    baseSalary: 35000000,
    numberOfDependents: 2,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 0,
    paidLeaveTaken: 0,
    unpaidLeaveTaken: 0,
    annualLeaveTaken: 0,
    annualLeaveBalance: 12,
    role: 'Admin',
    password: 'admin123',
    ...buildAuditFields('2024-01-05T08:00:00Z'),
  },
  {
    systemId: asSystemId(asSystemId('EMP000002')),
    id: asBusinessId('2'),
    fullName: 'Trần Thị B',
    workEmail: 'ttb@example.com',
    personalEmail: 'ttb.personal@gmail.com',
    phone: '0912345678',
    gender: 'Nữ',
    dob: '1992-02-02',
    permanentAddress: createAddress2Level('456 XYZ', 'Phường Thảo Điền', 'TP.HCM', '79'),
    temporaryAddress: null,
    jobTitle: 'Trưởng phòng',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2019-01-01',
    baseSalary: 25000000,
    numberOfDependents: 1,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 5,
    paidLeaveTaken: 4,
    unpaidLeaveTaken: 1,
    annualLeaveTaken: 4,
    annualLeaveBalance: 8,
    role: 'Manager',
    password: 'manager123',
    ...buildAuditFields('2024-02-05T08:00:00Z'),
  },
  {
    systemId: asSystemId(asSystemId('EMP000003')),
    id: asBusinessId('3'),
    fullName: 'Lê Văn C',
    workEmail: 'lvc@example.com',
    personalEmail: 'lvc.personal@gmail.com',
    phone: '0923456789',
    gender: 'Nam',
    dob: '1995-03-03',
    permanentAddress: createAddress3Level('789 DEF', 'Quận 3', 'Phường 9', 'TP.HCM', '79', 762),
    temporaryAddress: null,
    jobTitle: 'Kỹ sư',
    department: 'Kỹ thuật',
    branchSystemId: asSystemId('CN000002'),
    hireDate: '2021-01-01',
    baseSalary: 18000000,
    numberOfDependents: 0,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 2,
    paidLeaveTaken: 2,
    unpaidLeaveTaken: 0,
    annualLeaveTaken: 2,
    annualLeaveBalance: 10,
    role: 'Warehouse',
    password: 'warehouse123',
    ...buildAuditFields('2024-03-05T08:00:00Z'),
  },
  {
    systemId: asSystemId(asSystemId('EMP000004')),
    id: asBusinessId('4'),
    fullName: 'Võ Thị F',
    workEmail: 'vtf@example.com',
    personalEmail: 'vtf.personal@gmail.com',
    phone: '0934567890',
    gender: 'Nữ',
    dob: '1993-04-04',
    permanentAddress: createAddress2Level('321 GHI', 'Phường Tân Phú', 'TP.HCM', '79'),
    temporaryAddress: null,
    jobTitle: 'Trưởng nhóm',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2020-06-01',
    baseSalary: 20000000,
    numberOfDependents: 1,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 3,
    paidLeaveTaken: 2,
    unpaidLeaveTaken: 1,
    annualLeaveTaken: 2,
    annualLeaveBalance: 9,
    role: 'Sales',
    password: 'sales123',
    ...buildAuditFields('2024-04-05T08:00:00Z'),
  },
  {
    systemId: asSystemId('EMP000005'),
    id: asBusinessId('5'),
    fullName: 'Lê Văn Kho',
    workEmail: 'lvk@example.com',
    personalEmail: 'lvk.personal@gmail.com',
    phone: '0945678901',
    gender: 'Nam',
    dob: '1991-05-15',
    permanentAddress: createAddress3Level('45 Nguyễn Trãi', 'Quận 5', 'Phường 3', 'TP.HCM', '79', 763),
    temporaryAddress: null,
    jobTitle: 'Nhân viên kho',
    department: 'Kỹ thuật',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2021-03-01',
    baseSalary: 12000000,
    numberOfDependents: 0,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 1,
    paidLeaveTaken: 1,
    unpaidLeaveTaken: 0,
    annualLeaveTaken: 1,
    annualLeaveBalance: 11,
    role: 'Warehouse',
    password: 'warehouse123',
    ...buildAuditFields('2024-05-05T08:00:00Z'),
  },
  {
    systemId: asSystemId('EMP000006'),
    id: asBusinessId('6'),
    fullName: 'Phạm Văn D',
    workEmail: 'pvd@example.com',
    personalEmail: 'pvd.personal@gmail.com',
    phone: '0956789012',
    gender: 'Nam',
    dob: '1988-06-20',
    permanentAddress: createAddress2Level('78 Lê Lợi', 'Phường Bến Thành', 'TP.HCM', '79'),
    temporaryAddress: null,
    jobTitle: 'Nhân viên bán hàng',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000002'),
    hireDate: '2019-08-15',
    baseSalary: 15000000,
    numberOfDependents: 2,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 4,
    paidLeaveTaken: 3,
    unpaidLeaveTaken: 1,
    annualLeaveTaken: 3,
    annualLeaveBalance: 9,
    role: 'Sales',
    password: 'sales123',
    ...buildAuditFields('2024-06-05T08:00:00Z'),
  },
  {
    systemId: asSystemId('7'),
    id: asBusinessId('NV000007'),
    fullName: 'Hoàng Thị E',
    workEmail: 'hte@example.com',
    personalEmail: 'hte.personal@gmail.com',
    phone: '0967890123',
    gender: 'Nữ',
    dob: '1994-07-10',
    permanentAddress: createAddress3Level('112 Hai Bà Trưng', 'Quận 1', 'Phường Đa Kao', 'TP.HCM', '79', 760),
    temporaryAddress: null,
    jobTitle: 'Kế toán',
    department: 'Nhân sự',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2020-02-01',
    baseSalary: 16000000,
    numberOfDependents: 0,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 2,
    paidLeaveTaken: 2,
    unpaidLeaveTaken: 0,
    annualLeaveTaken: 2,
    annualLeaveBalance: 10,
    role: 'Admin',
    password: 'accountant123',
    ...buildAuditFields('2024-07-05T08:00:00Z'),
  },
  {
    systemId: asSystemId('EMP000008'),
    id: asBusinessId('8'),
    fullName: 'Nguyễn Văn G',
    workEmail: 'nvg@example.com',
    personalEmail: 'nvg.personal@gmail.com',
    phone: '0978901234',
    gender: 'Nam',
    dob: '1996-08-25',
    permanentAddress: createAddress2Level('234 Võ Văn Tần', 'Phường 5', 'TP.HCM', '79'),
    temporaryAddress: null,
    jobTitle: 'Nhân viên IT',
    department: 'Kỹ thuật',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2022-01-10',
    baseSalary: 18000000,
    numberOfDependents: 0,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 0,
    paidLeaveTaken: 0,
    unpaidLeaveTaken: 0,
    annualLeaveTaken: 0,
    annualLeaveBalance: 12,
    role: 'Admin',
    password: 'staff123',
    ...buildAuditFields('2024-08-05T08:00:00Z'),
  },
  {
    systemId: asSystemId('EMP000009'),
    id: asBusinessId('9'),
    fullName: 'Trần Thị H',
    workEmail: 'tth@example.com',
    personalEmail: 'tth.personal@gmail.com',
    phone: '0989012345',
    gender: 'Nữ',
    dob: '1997-09-05',
    permanentAddress: createAddress3Level('567 Nguyễn Đình Chiểu', 'Quận 3', 'Phường 5', 'TP.HCM', '79', 762),
    temporaryAddress: null,
    jobTitle: 'Nhân viên CSKH',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000002'),
    hireDate: '2021-06-01',
    baseSalary: 13000000,
    numberOfDependents: 0,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 3,
    paidLeaveTaken: 2,
    unpaidLeaveTaken: 1,
    annualLeaveTaken: 2,
    annualLeaveBalance: 10,
    role: 'Sales',
    password: 'staff123',
    ...buildAuditFields('2024-09-05T08:00:00Z'),
  },
  {
    systemId: asSystemId('EMP000010'),
    id: asBusinessId('10'),
    fullName: 'Đỗ Văn I',
    workEmail: 'dvi@example.com',
    personalEmail: 'dvi.personal@gmail.com',
    phone: '0990123456',
    gender: 'Nam',
    dob: '1989-10-12',
    permanentAddress: createAddress2Level('890 Cách Mạng Tháng 8', 'Phường 12', 'TP.HCM', '79'),
    temporaryAddress: null,
    jobTitle: 'Trưởng kho',
    department: 'Kỹ thuật',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2018-04-01',
    baseSalary: 22000000,
    numberOfDependents: 3,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 6,
    paidLeaveTaken: 5,
    unpaidLeaveTaken: 1,
    annualLeaveTaken: 5,
    annualLeaveBalance: 7,
    role: 'Warehouse',
    password: 'warehouse123',
    ...buildAuditFields('2024-10-05T08:00:00Z'),
  },
  {
    systemId: asSystemId('EMP000011'),
    id: asBusinessId('11'),
    fullName: 'Lý Thị K',
    workEmail: 'ltk@example.com',
    personalEmail: 'ltk.personal@gmail.com',
    phone: '0901234568',
    gender: 'Nữ',
    dob: '1995-11-18',
    permanentAddress: createAddress3Level('123 Trần Hưng Đạo', 'Quận 5', 'Phường 7', 'TP.HCM', '79', 763),
    temporaryAddress: null,
    jobTitle: 'Nhân viên Marketing',
    department: 'Marketing',
    branchSystemId: asSystemId('CN000001'),
    hireDate: '2022-03-15',
    baseSalary: 14000000,
    numberOfDependents: 0,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 1,
    paidLeaveTaken: 1,
    unpaidLeaveTaken: 0,
    annualLeaveTaken: 1,
    annualLeaveBalance: 11,
    role: 'Sales',
    password: 'staff123',
    ...buildAuditFields('2024-11-05T08:00:00Z'),
  },
  {
    systemId: asSystemId('EMP000012'),
    id: asBusinessId('12'),
    fullName: 'Bùi Văn L',
    workEmail: 'bvl@example.com',
    personalEmail: 'bvl.personal@gmail.com',
    phone: '0912345679',
    gender: 'Nam',
    dob: '1993-12-22',
    permanentAddress: createAddress2Level('456 Lý Thường Kiệt', 'Phường 14', 'TP.HCM', '79'),
    temporaryAddress: null,
    jobTitle: 'Nhân viên giao hàng',
    department: 'Kinh doanh',
    branchSystemId: asSystemId('CN000002'),
    hireDate: '2020-09-01',
    baseSalary: 11000000,
    numberOfDependents: 1,
    employmentStatus: 'Đang làm việc',
    employeeType: 'Chính thức',
    leaveTaken: 2,
    paidLeaveTaken: 2,
    unpaidLeaveTaken: 0,
    annualLeaveTaken: 2,
    annualLeaveBalance: 10,
    role: 'Warehouse',
    password: 'delivery123',
    ...buildAuditFields('2024-12-05T08:00:00Z'),
  },
];
