import { z } from 'zod';
import { sanitizeBusinessId } from '../../lib/id-utils';

// Phone number validation (Vietnam format)
const phoneRegex = /^(0|\+84)[3-9][0-9]{8}$/;

// Email validation
const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// National ID validation (CCCD 12 digits or CMND 9 digits)
const nationalIdRegex = /^(\d{9}|\d{12})$/;

export const employeeFormSchema = z.object({
  // Business ID - Optional (auto-generate if empty), custom format allowed
  id: z.string()
    .optional()
    .transform((val) => {
      // If empty, will be auto-generated by store
      if (!val || val.trim() === '') return '';
      // Sanitize: remove special chars, uppercase
      const sanitized = sanitizeBusinessId(val);
      if (!sanitized) {
        throw new Error('Mã không hợp lệ! Chỉ cho phép chữ và số, không có ký tự đặc biệt');
      }
      return sanitized;
    }),
  
  fullName: z.string()
    .min(2, "Họ tên phải có ít nhất 2 ký tự")
    .max(100, "Họ tên không được quá 100 ký tự"),
  
  gender: z.enum(['Nam', 'Nữ', 'Khác'], {
    message: "Vui lòng chọn giới tính"
  }),
  
  dob: z.date({
    message: "Vui lòng chọn ngày sinh",
  }).refine((date) => {
      const today = new Date();
      const age = today.getFullYear() - date.getFullYear();
      return age >= 18 && age <= 65;
    }, "Nhân viên phải từ 18-65 tuổi"),
  
  phone: z.string()
    .regex(phoneRegex, "Số điện thoại không hợp lệ (VD: 0912345678)"),
  
  workEmail: z.string()
    .regex(emailRegex, "Email không hợp lệ"),
  
  branchSystemId: z.string()
    .min(1, "Vui lòng chọn chi nhánh"),
  
  department: z.enum(["Kỹ thuật", "Nhân sự", "Kinh doanh", "Marketing"], {
    message: "Vui lòng chọn phòng ban"
  }).optional(),
  
  jobTitle: z.string()
    .min(1, "Vui lòng chọn chức danh"),
  
  hireDate: z.date({
    message: "Vui lòng chọn ngày vào làm",
  }),
  
  employmentStatus: z.enum(['Đang làm việc', 'Nghỉ việc', 'Tạm nghỉ'], {
    message: "Vui lòng chọn trạng thái"
  }),
  
  employeeType: z.enum(["Chính thức", "Thử việc", "Thực tập sinh", "Bán thời gian"], {
    message: "Vui lòng chọn loại nhân viên"
  }).optional(),

  contractType: z.enum(["Không xác định", "Thử việc", "1 năm", "2 năm", "3 năm", "Vô thời hạn"], {
    message: "Vui lòng chọn loại hợp đồng"
  }).optional(),

  contractNumber: z.string().optional(),
  contractStartDate: z.date().optional(),
  contractEndDate: z.date().optional(),

  // Optional fields
  personalEmail: z.string()
    .regex(emailRegex, "Email không hợp lệ")
    .optional()
    .or(z.literal('')),
  
  nationalId: z.string()
    .regex(nationalIdRegex, "CCCD/CMND không hợp lệ (9 hoặc 12 số)")
    .optional()
    .or(z.literal('')),
  
  address: z.string()
    .max(200, "Địa chỉ không được quá 200 ký tự")
    .optional(),
  
  permanentAddress: z.string()
    .max(200, "Địa chỉ thường trú không được quá 200 ký tự")
    .optional(),
  
  emergencyContact: z.string()
    .max(100, "Tên người liên hệ không được quá 100 ký tự")
    .optional(),
  
  emergencyPhone: z.string()
    .regex(phoneRegex, "Số điện thoại không hợp lệ")
    .optional()
    .or(z.literal('')),
  
  bankName: z.string()
    .max(100, "Tên ngân hàng không được quá 100 ký tự")
    .optional(),
  
  bankAccountNumber: z.string()
    .regex(/^\d{9,20}$/, "Số tài khoản phải từ 9-20 chữ số")
    .optional()
    .or(z.literal('')),
  
  baseSalary: z.number()
    .min(0, "Lương cơ bản không được âm")
    .optional(),

  socialInsuranceSalary: z.number()
    .min(0, "Lương đóng BHXH không được âm")
    .optional(),
  
  positionAllowance: z.number()
    .min(0, "Phụ cấp chức vụ không được âm")
    .optional(),

  mealAllowance: z.number()
    .min(0, "Phụ cấp ăn trưa không được âm")
    .optional(),

  otherAllowances: z.number()
    .min(0, "Phụ cấp khác không được âm")
    .optional(),
  
  leaveTaken: z.number()
    .min(0, "Số ngày phép đã nghỉ không được âm")
    .optional()
    .default(0),

  annualLeaveBalance: z.number()
    .min(0, "Số ngày phép không được âm")
    .max(365, "Số ngày phép không hợp lệ")
    .optional(),
  
  sickLeaveBalance: z.number()
    .min(0, "Số ngày nghỉ ốm không được âm")
    .max(365, "Số ngày nghỉ ốm không hợp lệ")
    .optional(),
  
  managerId: z.string().optional(),
  avatar: z.string().optional(),
  notes: z.string().optional(),
  
  // systemId for self-reference check
  systemId: z.string().optional(),
})
// Cross-field validations
.refine((data) => {
  // contractEndDate must be after contractStartDate
  if (data.contractStartDate && data.contractEndDate) {
    return data.contractEndDate > data.contractStartDate;
  }
  return true;
}, { 
  message: "Ngày kết thúc HĐ phải sau ngày bắt đầu HĐ",
  path: ["contractEndDate"]
})
.refine((data) => {
  // socialInsuranceSalary should not exceed baseSalary (warning level, allow but warn)
  // For strict validation, uncomment return false
  if (data.baseSalary && data.socialInsuranceSalary) {
    return data.socialInsuranceSalary <= data.baseSalary;
  }
  return true;
}, {
  message: "Lương đóng BHXH không nên lớn hơn lương cơ bản",
  path: ["socialInsuranceSalary"]
})
.refine((data) => {
  // managerId cannot be the same as employee's own systemId
  if (data.managerId && data.systemId && data.managerId === data.systemId) {
    return false;
  }
  return true;
}, {
  message: "Không thể tự làm quản lý của chính mình",
  path: ["managerId"]
});

export type EmployeeFormData = z.infer<typeof employeeFormSchema>;

// Validation helper for duplicate ID check (case-insensitive)
export const validateUniqueId = (
  id: string, 
  existingIds: string[], 
  currentId?: string
): boolean => {
  if (!id || id.trim() === '') return true; // Empty is valid (will auto-generate)
  
  const normalizedId = id.toUpperCase();
  const normalizedCurrentId = currentId?.toUpperCase();
  
  // If editing, exclude current ID from check
  const idsToCheck = existingIds.filter(existingId => {
    if (normalizedCurrentId && existingId.toUpperCase() === normalizedCurrentId) {
      return false; // Skip self
    }
    return true;
  });
  
  return !idsToCheck.some(existingId => existingId.toUpperCase() === normalizedId);
};
