import { z } from 'zod';
import { sanitizeBusinessId } from '../../lib/id-utils';

// Phone number validation (Vietnam format)
const phoneRegex = /^(0|\+84)[3-9][0-9]{8}$/;

// Email validation
const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// National ID validation (CCCD 12 digits or CMND 9 digits)
const nationalIdRegex = /^(\d{9}|\d{12})$/;

export const employeeFormSchema = z.object({
  // Business ID - Optional (auto-generate if empty), custom format allowed
  id: z.string()
    .optional()
    .transform((val) => {
      // If empty, will be auto-generated by store
      if (!val || val.trim() === '') return '';
      // Sanitize: remove special chars, uppercase
      const sanitized = sanitizeBusinessId(val);
      if (!sanitized) {
        throw new Error('Mã không hợp lệ! Chỉ cho phép chữ và số, không có ký tự đặc biệt');
      }
      return sanitized;
    }),
  
  fullName: z.string()
    .min(2, "Họ tên phải có ít nhất 2 ký tự")
    .max(100, "Họ tên không được quá 100 ký tự"),
  
  gender: z.enum(['Nam', 'Nữ', 'Khác'], {
    message: "Vui lòng chọn giới tính"
  }),
  
  dateOfBirth: z.string()
    .min(1, "Vui lòng chọn ngày sinh")
    .refine((date) => {
      const birthDate = new Date(date);
      const today = new Date();
      const age = today.getFullYear() - birthDate.getFullYear();
      return age >= 18 && age <= 65;
    }, "Nhân viên phải từ 18-65 tuổi"),
  
  phone: z.string()
    .regex(phoneRegex, "Số điện thoại không hợp lệ (VD: 0912345678)"),
  
  workEmail: z.string()
    .regex(emailRegex, "Email không hợp lệ"),
  
  branchId: z.string()
    .min(1, "Vui lòng chọn chi nhánh"),
  
  department: z.string()
    .min(1, "Vui lòng chọn phòng ban"),
  
  jobTitle: z.string()
    .min(1, "Vui lòng chọn chức danh"),
  
  hireDate: z.string()
    .min(1, "Vui lòng chọn ngày vào làm"),
  
  employmentStatus: z.enum(['Đang làm việc', 'Nghỉ việc', 'Tạm nghỉ'], {
    message: "Vui lòng chọn trạng thái"
  }),
  
  contractType: z.enum(['Thử việc', 'Chính thức', 'Hợp đồng', 'Thời vụ'], {
    message: "Vui lòng chọn loại hợp đồng"
  }),

  // Optional fields
  personalEmail: z.string()
    .regex(emailRegex, "Email không hợp lệ")
    .optional()
    .or(z.literal('')),
  
  nationalId: z.string()
    .regex(nationalIdRegex, "CCCD/CMND không hợp lệ (9 hoặc 12 số)")
    .optional()
    .or(z.literal('')),
  
  address: z.string()
    .max(200, "Địa chỉ không được quá 200 ký tự")
    .optional(),
  
  permanentAddress: z.string()
    .max(200, "Địa chỉ thường trú không được quá 200 ký tự")
    .optional(),
  
  emergencyContact: z.string()
    .max(100, "Tên người liên hệ không được quá 100 ký tự")
    .optional(),
  
  emergencyPhone: z.string()
    .regex(phoneRegex, "Số điện thoại không hợp lệ")
    .optional()
    .or(z.literal('')),
  
  bankName: z.string()
    .max(100, "Tên ngân hàng không được quá 100 ký tự")
    .optional(),
  
  bankAccountNumber: z.string()
    .regex(/^\d{9,20}$/, "Số tài khoản phải từ 9-20 chữ số")
    .optional()
    .or(z.literal('')),
  
  basicSalary: z.number()
    .min(0, "Lương cơ bản không được âm")
    .optional(),
  
  allowances: z.number()
    .min(0, "Phụ cấp không được âm")
    .optional(),
  
  annualLeaveBalance: z.number()
    .min(0, "Số ngày phép không được âm")
    .max(365, "Số ngày phép không hợp lệ")
    .optional(),
  
  sickLeaveBalance: z.number()
    .min(0, "Số ngày nghỉ ốm không được âm")
    .max(365, "Số ngày nghỉ ốm không hợp lệ")
    .optional(),
  
  managerId: z.string().optional(),
  avatar: z.string().optional(),
  notes: z.string().optional(),
});

export type EmployeeFormData = z.infer<typeof employeeFormSchema>;

// Validation helper for duplicate ID check (case-insensitive)
export const validateUniqueId = (
  id: string, 
  existingIds: string[], 
  currentId?: string
): boolean => {
  if (!id || id.trim() === '') return true; // Empty is valid (will auto-generate)
  
  const normalizedId = id.toUpperCase();
  const normalizedCurrentId = currentId?.toUpperCase();
  
  // If editing, exclude current ID from check
  const idsToCheck = existingIds.filter(existingId => {
    if (normalizedCurrentId && existingId.toUpperCase() === normalizedCurrentId) {
      return false; // Skip self
    }
    return true;
  });
  
  return !idsToCheck.some(existingId => existingId.toUpperCase() === normalizedId);
};
