import { asBusinessId, asSystemId } from '@/lib/id-types';
import type { Penalty, PenaltyType } from './types.ts';
import { buildSeedAuditFields } from '@/lib/seed-audit';

// =============================================
// PENALTY TYPES - Settings loại phạt
// =============================================
export const penaltyTypesData: PenaltyType[] = [
  {
    systemId: asSystemId('PENTYPE000001'),
    id: asBusinessId('LP001'),
    name: 'Làm hỏng hàng khách',
    description: 'Phạt khi nhân viên làm hỏng hàng hóa của khách hàng',
    defaultAmount: 200000,
    category: 'complaint',
    isActive: true,
    order: 1,
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
  {
    systemId: asSystemId('PENTYPE000002'),
    id: asBusinessId('LP002'),
    name: 'Giao thiếu hàng',
    description: 'Phạt khi nhân viên giao thiếu hàng cho khách',
    defaultAmount: 100000,
    category: 'complaint',
    isActive: true,
    order: 2,
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
  {
    systemId: asSystemId('PENTYPE000003'),
    id: asBusinessId('LP003'),
    name: 'Đóng gói sai quy cách',
    description: 'Phạt khi đóng gói không đúng quy định',
    defaultAmount: 50000,
    category: 'complaint',
    isActive: true,
    order: 3,
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
  {
    systemId: asSystemId('PENTYPE000004'),
    id: asBusinessId('LP004'),
    name: 'Đi làm trễ',
    description: 'Phạt khi đi làm trễ không có lý do',
    defaultAmount: 100000,
    category: 'attendance',
    isActive: true,
    order: 4,
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
  {
    systemId: asSystemId('PENTYPE000005'),
    id: asBusinessId('LP005'),
    name: 'Nghỉ không phép',
    description: 'Phạt khi nghỉ làm không xin phép',
    defaultAmount: 200000,
    category: 'attendance',
    isActive: true,
    order: 5,
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
  {
    systemId: asSystemId('PENTYPE000006'),
    id: asBusinessId('LP006'),
    name: 'Quên chấm công',
    description: 'Phạt khi quên chấm công vào/ra',
    defaultAmount: 50000,
    category: 'attendance',
    isActive: true,
    order: 6,
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
  {
    systemId: asSystemId('PENTYPE000007'),
    id: asBusinessId('LP007'),
    name: 'Không hoàn thành KPI',
    description: 'Phạt khi không đạt chỉ tiêu KPI',
    defaultAmount: 150000,
    category: 'performance',
    isActive: true,
    order: 7,
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
  {
    systemId: asSystemId('PENTYPE000008'),
    id: asBusinessId('LP008'),
    name: 'Vi phạm nội quy',
    description: 'Phạt khi vi phạm nội quy công ty',
    defaultAmount: 100000,
    category: 'other',
    isActive: true,
    order: 8,
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
  {
    systemId: asSystemId('PENTYPE000009'),
    id: asBusinessId('LP009'),
    name: 'Thu hồi chi phí phát sinh',
    description: 'Thu hồi chi phí phát sinh từ khiếu nại do nhân viên gây ra',
    defaultAmount: 0, // Số tiền sẽ được tính theo chi phí thực tế
    category: 'complaint',
    isActive: true,
    order: 0, // Đặt lên đầu trong danh sách complaint
    ...buildSeedAuditFields({ createdAt: '2025-01-01T00:00:00Z' }),
  },
];

// =============================================
// PENALTIES - Phiếu phạt
// =============================================
export const data: Penalty[] = [
  {
    systemId: asSystemId('PENALTY000001'),
    id: asBusinessId('PF000001'),
    employeeSystemId: asSystemId('EMP000003'),
    employeeName: 'Lê Văn Cường',
    reason: 'Đi làm trễ 30 phút không có lý do.',
    amount: 100000,
    issueDate: '2025-10-28',
    status: 'Đã thanh toán',
    issuerName: 'Nguyễn Văn An',
    penaltyTypeSystemId: asSystemId('PENTYPE000004'),
    penaltyTypeName: 'Đi làm trễ',
    category: 'attendance',
    ...buildSeedAuditFields({ createdAt: '2025-10-28T08:00:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000002'),
    id: asBusinessId('PF000002'),
    employeeSystemId: asSystemId('EMP000005'),
    employeeName: 'Hoàng Văn Em',
    reason: 'Không tuân thủ đồng phục công ty.',
    amount: 50000,
    issueDate: '2025-11-02',
    status: 'Chưa thanh toán',
    issuerName: 'Phạm Thị Dung',
    penaltyTypeSystemId: asSystemId('PENTYPE000008'),
    penaltyTypeName: 'Vi phạm nội quy',
    category: 'other',
    ...buildSeedAuditFields({ createdAt: '2025-11-02T08:00:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000003'),
    id: asBusinessId('PF000003'),
    employeeSystemId: asSystemId('EMP000014'),
    employeeName: 'Ngô Thị Phương',
    reason: 'Gửi báo cáo tuần chậm 1 ngày.',
    amount: 50000,
    issueDate: '2025-11-04',
    status: 'Chưa thanh toán',
    issuerName: 'Đỗ Hùng',
    penaltyTypeSystemId: asSystemId('PENTYPE000007'),
    penaltyTypeName: 'Không hoàn thành KPI',
    category: 'performance',
    ...buildSeedAuditFields({ createdAt: '2025-11-04T08:00:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000004'),
    id: asBusinessId('PF000004'),
    employeeSystemId: asSystemId('EMP000003'),
    employeeName: 'Lê Văn Cường',
    reason: 'Quên chấm công khi ra về.',
    amount: 50000,
    issueDate: '2025-11-05',
    status: 'Đã hủy',
    issuerName: 'Phạm Thị Dung',
    penaltyTypeSystemId: asSystemId('PENTYPE000006'),
    penaltyTypeName: 'Quên chấm công',
    category: 'attendance',
    ...buildSeedAuditFields({ createdAt: '2025-11-05T08:00:00Z' }),
  },
  // =============================================
  // PENALTIES FOR DECEMBER 2025 - Test data
  // =============================================
  {
    systemId: asSystemId('PENALTY000005'),
    id: asBusinessId('PF000005'),
    employeeSystemId: asSystemId('EMP000001'),
    employeeName: 'Nguyễn Văn A',
    reason: 'Đi làm trễ 15 phút ngày 02/12.',
    amount: 100000,
    issueDate: '2025-12-02',
    status: 'Chưa thanh toán',
    issuerName: 'Trần Thị B',
    issuerSystemId: asSystemId('EMP000002'),
    penaltyTypeSystemId: asSystemId('PENTYPE000004'),
    penaltyTypeName: 'Đi làm trễ',
    category: 'attendance',
    ...buildSeedAuditFields({ createdAt: '2025-12-02T08:30:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000006'),
    id: asBusinessId('PF000006'),
    employeeSystemId: asSystemId('EMP000001'),
    employeeName: 'Nguyễn Văn A',
    reason: 'Quên chấm công khi ra về ngày 03/12.',
    amount: 50000,
    issueDate: '2025-12-03',
    status: 'Chưa thanh toán',
    issuerName: 'Trần Thị B',
    issuerSystemId: asSystemId('EMP000002'),
    penaltyTypeSystemId: asSystemId('PENTYPE000006'),
    penaltyTypeName: 'Quên chấm công',
    category: 'attendance',
    ...buildSeedAuditFields({ createdAt: '2025-12-03T18:00:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000007'),
    id: asBusinessId('PF000007'),
    employeeSystemId: asSystemId('EMP000002'),
    employeeName: 'Trần Thị B',
    reason: 'Không hoàn thành báo cáo KPI tuần.',
    amount: 150000,
    issueDate: '2025-12-05',
    status: 'Chưa thanh toán',
    issuerName: 'Nguyễn Văn A',
    issuerSystemId: asSystemId('EMP000001'),
    penaltyTypeSystemId: asSystemId('PENTYPE000007'),
    penaltyTypeName: 'Không hoàn thành KPI',
    category: 'performance',
    ...buildSeedAuditFields({ createdAt: '2025-12-05T10:00:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000008'),
    id: asBusinessId('PF000008'),
    employeeSystemId: asSystemId('EMP000003'),
    employeeName: 'Lê Văn C',
    reason: 'Đóng gói hàng không đúng quy cách, gây hư hỏng hàng hóa.',
    amount: 200000,
    issueDate: '2025-12-04',
    status: 'Chưa thanh toán',
    issuerName: 'Trần Thị B',
    issuerSystemId: asSystemId('EMP000002'),
    penaltyTypeSystemId: asSystemId('PENTYPE000003'),
    penaltyTypeName: 'Đóng gói sai quy cách',
    category: 'complaint',
    ...buildSeedAuditFields({ createdAt: '2025-12-04T14:30:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000009'),
    id: asBusinessId('PF000009'),
    employeeSystemId: asSystemId('EMP000003'),
    employeeName: 'Lê Văn C',
    reason: 'Nghỉ không phép ngày 06/12.',
    amount: 200000,
    issueDate: '2025-12-06',
    status: 'Chưa thanh toán',
    issuerName: 'Nguyễn Văn A',
    issuerSystemId: asSystemId('EMP000001'),
    penaltyTypeSystemId: asSystemId('PENTYPE000005'),
    penaltyTypeName: 'Nghỉ không phép',
    category: 'attendance',
    ...buildSeedAuditFields({ createdAt: '2025-12-06T09:00:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000010'),
    id: asBusinessId('PF000010'),
    employeeSystemId: asSystemId('EMP000004'),
    employeeName: 'Võ Thị F',
    reason: 'Vi phạm nội quy - sử dụng điện thoại trong giờ làm việc.',
    amount: 100000,
    issueDate: '2025-12-05',
    status: 'Chưa thanh toán',
    issuerName: 'Trần Thị B',
    issuerSystemId: asSystemId('EMP000002'),
    penaltyTypeSystemId: asSystemId('PENTYPE000008'),
    penaltyTypeName: 'Vi phạm nội quy',
    category: 'other',
    ...buildSeedAuditFields({ createdAt: '2025-12-05T15:45:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000011'),
    id: asBusinessId('PF000011'),
    employeeSystemId: asSystemId('EMP000004'),
    employeeName: 'Võ Thị F',
    reason: 'Đi làm trễ 25 phút ngày 08/12.',
    amount: 100000,
    issueDate: '2025-12-08',
    status: 'Chưa thanh toán',
    issuerName: 'Nguyễn Văn A',
    issuerSystemId: asSystemId('EMP000001'),
    penaltyTypeSystemId: asSystemId('PENTYPE000004'),
    penaltyTypeName: 'Đi làm trễ',
    category: 'attendance',
    ...buildSeedAuditFields({ createdAt: '2025-12-08T08:25:00Z' }),
  },
  // November 2025 - Additional penalties
  {
    systemId: asSystemId('PENALTY000012'),
    id: asBusinessId('PF000012'),
    employeeSystemId: asSystemId('EMP000001'),
    employeeName: 'Nguyễn Văn A',
    reason: 'Giao thiếu hàng cho khách, đơn hàng #DH12345.',
    amount: 100000,
    issueDate: '2025-11-15',
    status: 'Chưa thanh toán',
    issuerName: 'Trần Thị B',
    issuerSystemId: asSystemId('EMP000002'),
    penaltyTypeSystemId: asSystemId('PENTYPE000002'),
    penaltyTypeName: 'Giao thiếu hàng',
    category: 'complaint',
    ...buildSeedAuditFields({ createdAt: '2025-11-15T16:00:00Z' }),
  },
  {
    systemId: asSystemId('PENALTY000013'),
    id: asBusinessId('PF000013'),
    employeeSystemId: asSystemId('EMP000002'),
    employeeName: 'Trần Thị B',
    reason: 'Quên chấm công 2 lần trong tuần.',
    amount: 100000,
    issueDate: '2025-11-20',
    status: 'Chưa thanh toán',
    issuerName: 'Nguyễn Văn A',
    issuerSystemId: asSystemId('EMP000001'),
    penaltyTypeSystemId: asSystemId('PENTYPE000006'),
    penaltyTypeName: 'Quên chấm công',
    category: 'attendance',
    ...buildSeedAuditFields({ createdAt: '2025-11-20T17:30:00Z' }),
  },
];
