// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Strip quotes from DATABASE_URL if present (dotenv may include them)
let databaseUrl = process.env["DATABASE_URL"];
if (databaseUrl) {
  databaseUrl = databaseUrl.replace(/^["']|["']$/g, '');
}

export default defineConfig({
  schema: "prisma/schema",  // Multi-file schema directory
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
