import type { Task, TaskAssignee } from './types.ts';
import { asSystemId, asBusinessId } from '../../lib/id-types';

export const data: Task[] = [
  {
    systemId: asSystemId('TASK000001'),
    id: asBusinessId('CVNB000001'),
    title: 'Thiết kế giao diện trang chủ mới',
    description: 'Thiết kế lại giao diện trang chủ theo phong cách hiện đại, tập trung vào UX/UI',
    assignees: [
      {
        systemId: asSystemId('assignee-1-1'),
        employeeSystemId: asSystemId('EMP-001'),
        employeeName: 'Nguyễn Văn An',
        role: 'owner',
        assignedAt: '2025-11-01T08:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
      {
        systemId: asSystemId('assignee-1-2'),
        employeeSystemId: asSystemId('EMP-005'),
        employeeName: 'Võ Thị Mai',
        role: 'reviewer',
        assignedAt: '2025-11-01T08:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
    ],
    assigneeId: asSystemId('EMP-001'),
    assigneeName: 'Nguyễn Văn An',
    assignerId: asSystemId('EMP-002'),
    assignerName: 'Trần Thị Bích',
    priority: 'Cao',
    status: 'Đang thực hiện',
    startDate: '2025-11-01',
    dueDate: '2025-11-15',
    estimatedHours: 40,
    actualHours: 20,
    progress: 50,
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2025-11-08T10:30:00Z',
    createdBy: asSystemId('EMP-002'),
    updatedBy: asSystemId('EMP-001')
  },
  {
    systemId: asSystemId('TASK000002'),
    id: asBusinessId('CVNB000002'),
    title: 'Phát triển API quản lý đơn hàng',
    description: 'Xây dựng REST API cho module quản lý đơn hàng, bao gồm CRUD operations và báo cáo',
    assignees: [
      {
        systemId: asSystemId('assignee-2-1'),
        employeeSystemId: asSystemId('EMP-003'),
        employeeName: 'Lê Hoàng Nam',
        role: 'owner',
        assignedAt: '2025-11-05T09:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
      {
        systemId: asSystemId('assignee-2-2'),
        employeeSystemId: asSystemId('EMP-004'),
        employeeName: 'Phạm Minh Tuấn',
        role: 'contributor',
        assignedAt: '2025-11-05T09:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
    ],
    assigneeId: asSystemId('EMP-003'),
    assigneeName: 'Lê Hoàng Nam',
    assignerId: asSystemId('EMP-002'),
    assignerName: 'Trần Thị Bích',
    priority: 'Khẩn cấp',
    status: 'Đang thực hiện',
    startDate: '2025-11-05',
    dueDate: '2025-11-12',
    estimatedHours: 30,
    actualHours: 15,
    progress: 60,
    createdAt: '2025-11-05T09:00:00Z',
    updatedAt: '2025-11-08T14:20:00Z',
    createdBy: asSystemId('EMP-002'),
    updatedBy: asSystemId('EMP-003')
  },
  {
    systemId: asSystemId('TASK000003'),
    id: asBusinessId('CVNB000003'),
    title: 'Viết test cases cho module thanh toán',
    description: 'Viết unit tests và integration tests cho các chức năng thanh toán',
    assignees: [
      {
        systemId: asSystemId('assignee-3-1'),
        employeeSystemId: asSystemId('EMP-004'),
        employeeName: 'Phạm Minh Tuấn',
        role: 'owner',
        assignedAt: '2025-11-07T11:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
    ],
    assigneeId: asSystemId('EMP-004'),
    assigneeName: 'Phạm Minh Tuấn',
    assignerId: asSystemId('EMP-002'),
    assignerName: 'Trần Thị Bích',
    priority: 'Trung bình',
    status: 'Chưa bắt đầu',
    startDate: '2025-11-10',
    dueDate: '2025-11-20',
    estimatedHours: 20,
    progress: 0,
    createdAt: '2025-11-07T11:00:00Z',
    updatedAt: '2025-11-07T11:00:00Z',
    createdBy: asSystemId('EMP-002'),
    updatedBy: asSystemId('EMP-002')
  },
  {
    systemId: asSystemId('TASK000004'),
    id: asBusinessId('CVNB000004'),
    title: 'Tối ưu hiệu suất database',
    description: 'Phân tích và tối ưu các queries chậm, thêm indexes phù hợp',
    assignees: [
      {
        systemId: asSystemId('assignee-4-1'),
        employeeSystemId: asSystemId('EMP-003'),
        employeeName: 'Lê Hoàng Nam',
        role: 'owner',
        assignedAt: '2025-10-28T08:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
    ],
    assigneeId: asSystemId('EMP-003'),
    assigneeName: 'Lê Hoàng Nam',
    assignerId: asSystemId('EMP-002'),
    assignerName: 'Trần Thị Bích',
    priority: 'Cao',
    status: 'Hoàn thành',
    startDate: '2025-10-28',
    dueDate: '2025-11-05',
    completedDate: '2025-11-04',
    estimatedHours: 16,
    actualHours: 14,
    progress: 100,
    createdAt: '2025-10-28T08:00:00Z',
    updatedAt: '2025-11-04T16:30:00Z',
    createdBy: asSystemId('EMP-002'),
    updatedBy: asSystemId('EMP-003')
  },
  {
    systemId: asSystemId('TASK000005'),
    id: asBusinessId('CVNB000005'),
    title: 'Cập nhật documentation cho API',
    description: 'Viết tài liệu chi tiết cho các API endpoints mới',
    assignees: [
      {
        systemId: asSystemId('assignee-5-1'),
        employeeSystemId: asSystemId('EMP-005'),
        employeeName: 'Võ Thị Mai',
        role: 'owner',
        assignedAt: '2025-11-06T10:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
      {
        systemId: asSystemId('assignee-5-2'),
        employeeSystemId: asSystemId('EMP-001'),
        employeeName: 'Nguyễn Văn An',
        role: 'contributor',
        assignedAt: '2025-11-06T10:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
      {
        systemId: asSystemId('assignee-5-3'),
        employeeSystemId: asSystemId('EMP-003'),
        employeeName: 'Lê Hoàng Nam',
        role: 'reviewer',
        assignedAt: '2025-11-06T10:00:00Z',
        assignedBy: asSystemId('EMP-002'),
      },
    ],
    assigneeId: asSystemId('EMP-005'),
    assigneeName: 'Võ Thị Mai',
    assignerId: asSystemId('EMP-002'),
    assignerName: 'Trần Thị Bích',
    priority: 'Thấp',
    status: 'Đang chờ',
    startDate: '2025-11-08',
    dueDate: '2025-11-18',
    estimatedHours: 12,
    progress: 0,
    createdAt: '2025-11-08T11:00:00Z',
    updatedAt: '2025-11-08T09:00:00Z',
    createdBy: asSystemId('EMP-002'),
    updatedBy: asSystemId('EMP-005')
  }
];

