import type { TaskTemplate } from './template-types';
import { asSystemId } from '../../lib/id-types';

export const templateData: TaskTemplate[] = [
  {
    systemId: asSystemId('TEMPLATE00000001'),
    id: 'TMPL-001',
    name: 'API Development Standard',
    description: 'Quy trình chuẩn phát triển REST API với testing và documentation',
    category: 'Development',
    priority: 'Cao',
    estimatedHours: 24,
    assigneeRoles: [
      { role: 'owner', description: 'Backend Developer' },
      { role: 'reviewer', description: 'Tech Lead' },
    ],
    subtasks: [
      { title: 'Thiết kế API schema & endpoints', estimatedHours: 4, order: 1 },
      { title: 'Implement database models', estimatedHours: 3, order: 2 },
      { title: 'Viết business logic & controllers', estimatedHours: 6, order: 3 },
      { title: 'Viết unit tests (coverage >80%)', estimatedHours: 5, order: 4 },
      { title: 'Viết API documentation (Swagger)', estimatedHours: 3, order: 5 },
      { title: 'Code review & refactor', estimatedHours: 3, order: 6 },
    ],
    checklistItems: [
      'Kiểm tra authentication & authorization',
      'Validate input data',
      'Handle errors properly',
      'Add request/response logging',
      'Test edge cases',
    ],
    usageCount: 15,
    isActive: true,
    createdBy: 'EMP-002',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-11-01T10:00:00Z',
  },
  {
    systemId: asSystemId('TEMPLATE00000002'),
    id: 'TMPL-002',
    name: 'UI/UX Design Process',
    description: 'Quy trình thiết kế giao diện từ wireframe đến prototype',
    category: 'Design',
    priority: 'Trung bình',
    estimatedHours: 80,
    assigneeRoles: [
      { role: 'owner', description: 'UI/UX Designer' },
      { role: 'contributor', description: 'Product Manager' },
      { role: 'reviewer', description: 'Design Lead' },
    ],
    subtasks: [
      { title: 'Research & gather requirements', estimatedHours: 4, order: 1 },
      { title: 'Create user personas & user flows', estimatedHours: 4, order: 2 },
      { title: 'Wireframe low-fidelity mockups', estimatedHours: 6, order: 3 },
      { title: 'Design high-fidelity UI screens', estimatedHours: 8, order: 4 },
      { title: 'Create interactive prototype', estimatedHours: 6, order: 5 },
      { title: 'User testing & feedback', estimatedHours: 4, order: 6 },
    ],
    checklistItems: [
      'Đảm bảo responsive design (mobile, tablet, desktop)',
      'Check accessibility standards (WCAG)',
      'Kiểm tra color contrast',
      'Design system consistency',
      'Export assets for developers',
    ],
    usageCount: 8,
    isActive: true,
    createdBy: 'EMP-001',
    createdAt: '2025-02-10T09:00:00Z',
    updatedAt: '2025-10-20T14:30:00Z',
  },
  {
    systemId: asSystemId('TEMPLATE00000003'),
    id: 'TMPL-003',
    name: 'Content Marketing Campaign',
    description: 'Template cho chiến dịch marketing nội dung',
    category: 'Marketing',
    priority: 'Trung bình',
    estimatedHours: 60,
    assigneeRoles: [
      { role: 'owner', description: 'Content Marketing Manager' },
      { role: 'contributor', description: 'Content Writer' },
      { role: 'contributor', description: 'Graphic Designer' },
      { role: 'reviewer', description: 'Marketing Director' },
    ],
    subtasks: [
      { title: 'Define campaign objectives & KPIs', estimatedHours: 3, order: 1 },
      { title: 'Research target audience & competitors', estimatedHours: 5, order: 2 },
      { title: 'Create content calendar (1 month)', estimatedHours: 4, order: 3 },
      { title: 'Write blog posts & articles', estimatedHours: 12, order: 4 },
      { title: 'Design social media graphics', estimatedHours: 8, order: 5 },
      { title: 'Schedule & publish content', estimatedHours: 4, order: 6 },
      { title: 'Track analytics & report results', estimatedHours: 4, order: 7 },
    ],
    checklistItems: [
      'SEO optimization (keywords, meta tags)',
      'Include clear CTAs',
      'A/B test headlines',
      'Monitor engagement metrics',
      'Respond to comments & messages',
    ],
    usageCount: 12,
    isActive: true,
    createdBy: 'EMP-002',
    createdAt: '2025-03-05T11:00:00Z',
    updatedAt: '2025-11-05T16:00:00Z',
  },
  {
    systemId: asSystemId('TEMPLATE00000004'),
    id: 'TMPL-004',
    name: 'Customer Onboarding Process',
    description: 'Quy trình onboarding khách hàng mới',
    category: 'Support',
    priority: 'Cao',
    estimatedHours: 100,
    assigneeRoles: [
      { role: 'owner', description: 'Customer Success Manager' },
      { role: 'contributor', description: 'Support Specialist' },
    ],
    subtasks: [
      { title: 'Send welcome email & schedule kickoff call', estimatedHours: 1, order: 1 },
      { title: 'Conduct product demo & training', estimatedHours: 3, order: 2 },
      { title: 'Set up customer account & configurations', estimatedHours: 2, order: 3 },
      { title: 'Provide documentation & resources', estimatedHours: 2, order: 4 },
      { title: 'Follow-up check-in (Week 1)', estimatedHours: 2, order: 5 },
      { title: 'Follow-up check-in (Week 2)', estimatedHours: 2, order: 6 },
      { title: 'Gather feedback & optimize', estimatedHours: 2, order: 7 },
      { title: 'Mark onboarding complete', estimatedHours: 2, order: 8 },
    ],
    checklistItems: [
      'Verify customer contact information',
      'Share quick-start guide',
      'Add to email automation sequence',
      'Create customer success plan',
      'Assign account manager',
    ],
    usageCount: 25,
    isActive: true,
    createdBy: 'EMP-005',
    createdAt: '2025-04-12T08:30:00Z',
    updatedAt: '2025-11-10T12:00:00Z',
  },
  {
    systemId: asSystemId('TEMPLATE00000005'),
    id: 'TMPL-005',
    name: 'Bug Fix Standard',
    description: 'Quy trình chuẩn xử lý bug với testing và rollback plan',
    category: 'Development',
    priority: 'Khẩn cấp',
    estimatedHours: 20,
    assigneeRoles: [
      { role: 'owner', description: 'Developer (assigned to bug)' },
      { role: 'reviewer', description: 'QA Engineer' },
    ],
    subtasks: [
      { title: 'Reproduce bug & analyze root cause', estimatedHours: 2, order: 1 },
      { title: 'Implement fix & write test cases', estimatedHours: 3, order: 2 },
      { title: 'Code review & QA testing', estimatedHours: 1, order: 3 },
      { title: 'Deploy to staging & verify fix', estimatedHours: 1, order: 4 },
      { title: 'Deploy to production', estimatedHours: 0.5, order: 5 },
      { title: 'Monitor for regressions', estimatedHours: 0.5, order: 6 },
    ],
    checklistItems: [
      'Create rollback plan',
      'Add logging for debugging',
      'Update documentation if needed',
      'Notify affected users',
      'Post-mortem analysis',
    ],
    usageCount: 42,
    isActive: true,
    createdBy: 'EMP-003',
    createdAt: '2025-01-20T10:00:00Z',
    updatedAt: '2025-11-12T15:30:00Z',
  },
];
