import { createCrudStore } from '../../lib/store-factory';
import { templateData as initialData } from './template-data';
import type { TaskTemplate, UseTemplateOptions } from './template-types';
import type { Task, TaskAssignee } from './types';
import { asSystemId } from '../../lib/id-types';

const baseStore = createCrudStore<TaskTemplate>(initialData, 'task-templates');

export const useTaskTemplateStore = () => {
  const store = baseStore();

  return {
    ...store,

    // Get templates by category
    getByCategory: (category: string) => {
      return store.data.filter(t => t.category === category && t.isActive);
    },

    // Get most used templates
    getMostUsed: (limit: number = 5) => {
      return [...store.data]
        .filter(t => t.isActive)
        .sort((a, b) => b.usageCount - a.usageCount)
        .slice(0, limit);
    },

    // Search templates
    search: (query: string) => {
      const lowerQuery = query.toLowerCase();
      return store.data.filter(t => 
        t.isActive && (
          t.name.toLowerCase().includes(lowerQuery) ||
          t.description.toLowerCase().includes(lowerQuery)
        )
      );
    },

    // Toggle template active status
    toggleActive: (templateId: string) => {
      const template = store.findById(asSystemId(templateId));
      if (!template) return;

      store.update(asSystemId(templateId), {
        ...template,
        isActive: !template.isActive,
        updatedAt: new Date().toISOString(),
      });
    },

    // Increment usage count
    incrementUsage: (templateId: string) => {
      const template = store.findById(asSystemId(templateId));
      if (!template) return;

      store.update(asSystemId(templateId), {
        ...template,
        usageCount: template.usageCount + 1,
        updatedAt: new Date().toISOString(),
      });
    },

    // Create task from template
    createTaskFromTemplate: (options: UseTemplateOptions): Omit<Task, 'systemId'> => {
      const template = store.findById(asSystemId(options.templateId));
      if (!template) {
        throw new Error('Template not found');
      }

      // Increment template usage count
      store.update(asSystemId(options.templateId), {
        ...template,
        usageCount: template.usageCount + 1,
        updatedAt: new Date().toISOString(),
      });

      // Build description with checklist
      let description = template.description;
      if (template.checklistItems && template.checklistItems.length > 0) {
        description += '\n\n**Checklist:**\n';
        template.checklistItems.forEach(item => {
          description += `- [ ] ${item}\n`;
        });
      }

      // Convert template subtasks to task subtasks
      const subtasks = template.subtasks.map((st, idx) => ({
        id: `subtask-${Date.now()}-${idx}`,
        title: st.title,
        completed: false,
      }));

      // Get owner for backward compatibility
      const owner = options.assignees.find(a => a.role === 'owner') || options.assignees[0];

      // Create task object
      const task: Omit<Task, 'systemId'> = {
        id: '', // Will be auto-generated by task store
        title: options.title,
        description,
        assignees: options.assignees,
        assigneeId: owner?.employeeSystemId || '',
        assigneeName: owner?.employeeName || '',
        assignerId: 'CURRENT_USER', // Will be replaced by actual user
        assignerName: 'Current User',
        priority: template.priority,
        status: 'Chưa bắt đầu',
        startDate: new Date().toISOString().split('T')[0],
        dueDate: options.dueDate,
        estimatedHours: template.estimatedHours,
        progress: 0,
        subtasks,
        activities: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        createdBy: 'CURRENT_USER',
        updatedBy: 'CURRENT_USER',
      };

      return task;
    },

    // Duplicate template
    duplicate: (templateId: string, newName?: string) => {
      const template = store.findById(asSystemId(templateId));
      if (!template) return null;

      const duplicated: Omit<TaskTemplate, 'systemId'> = {
        ...template,
        id: '', // Will be auto-generated
        name: newName || `${template.name} (Copy)`,
        usageCount: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        createdBy: 'CURRENT_USER',
      };

      return store.add(duplicated);
    },
  };
};
