import type { Payment } from './types.ts';
import { asSystemId, asBusinessId } from '../../lib/id-types';

export const data: Payment[] = [
  {
    systemId: asSystemId('PAYMENT000001'),
    id: asBusinessId('PC000001'),
    date: '2024-11-12',
    amount: 2000000,
    recipientTypeSystemId: asSystemId('NHACUNGCAP'),
    recipientTypeName: 'Nhà cung cấp',
    recipientName: 'Công ty TNHH ABC',
    recipientSystemId: asSystemId('SUPPLIER000001'),
    description: 'Thanh toán tiền hàng nhập kho',
    paymentMethodSystemId: asSystemId('CHUYENKHOAN'),
    paymentMethodName: 'Chuyển khoản',
    accountSystemId: asSystemId('ACCOUNT000002'),
    paymentReceiptTypeSystemId: asSystemId('PT_PURCHASE'),
    paymentReceiptTypeName: 'Mua hàng',
    branchSystemId: asSystemId('BRANCH000001'),
    branchName: 'Chi nhánh 1',
    createdBy: asSystemId('admin'),
    createdAt: '2024-11-12T09:00:00Z',
    status: 'completed',
    category: 'purchase',
    affectsDebt: false,
    runningBalance: 501000000,
  },
  {
    systemId: asSystemId('PAYMENT000002'),
    id: asBusinessId('PC000002'),
    date: '2024-11-13',
    amount: 1500000,
    recipientTypeSystemId: asSystemId('NHANVIEN'),
    recipientTypeName: 'Nhân viên',
    recipientName: 'Lê Văn C',
    recipientSystemId: asSystemId('EMP000001'),
    description: 'Tạm ứng lương tháng 11',
    paymentMethodSystemId: asSystemId('TIENMAT'),
    paymentMethodName: 'Tiền mặt',
    accountSystemId: asSystemId('ACCOUNT000001'),
    paymentReceiptTypeSystemId: asSystemId('PT_SALARY'),
    paymentReceiptTypeName: 'Chi lương',
    branchSystemId: asSystemId('BRANCH000001'),
    branchName: 'Chi nhánh 1',
    createdBy: asSystemId('admin'),
    createdAt: '2024-11-13T15:00:00Z',
    status: 'completed',
    category: 'salary',
    affectsDebt: false,
    runningBalance: 1730738671,
  },
];
