import type { Payment } from './types.ts';
import { asSystemId, asBusinessId } from '../../lib/id-types';

export const data: Payment[] = [
  {
    systemId: asSystemId('PAYMENT000001'),
    id: asBusinessId('PC000001'),
    date: '2024-11-12',
    amount: 2000000,
    recipientTypeSystemId: 'NHACUNGCAP',
    recipientTypeName: 'Nhà cung cấp',
    recipientName: 'Công ty TNHH ABC',
    recipientSystemId: 'SUPPLIER000001',
    description: 'Thanh toán tiền hàng nhập kho',
    paymentMethodSystemId: 'CHUYENKHOAN',
    paymentMethodName: 'Chuyển khoản',
    accountSystemId: 'ACC_VCB',
    paymentReceiptTypeSystemId: 'PT_PURCHASE',
    paymentReceiptTypeName: 'Mua hàng',
    branchSystemId: 'BRANCH000001',
    branchName: 'Chi nhánh 1',
    createdBy: 'admin',
    createdAt: '2024-11-12T09:00:00Z',
    status: 'completed',
    category: 'purchase',
    affectsDebt: false,
    runningBalance: 501000000,
  },
  {
    systemId: asSystemId('PAYMENT000002'),
    id: asBusinessId('PC000002'),
    date: '2024-11-13',
    amount: 1500000,
    recipientTypeSystemId: 'NHANVIEN',
    recipientTypeName: 'Nhân viên',
    recipientName: 'Lê Văn C',
    recipientSystemId: 'EMP000001',
    description: 'Tạm ứng lương tháng 11',
    paymentMethodSystemId: 'TIENMAT',
    paymentMethodName: 'Tiền mặt',
    accountSystemId: 'ACC_CASH',
    paymentReceiptTypeSystemId: 'PT_SALARY',
    paymentReceiptTypeName: 'Chi lương',
    branchSystemId: 'BRANCH000001',
    branchName: 'Chi nhánh 1',
    createdBy: 'admin',
    createdAt: '2024-11-13T15:00:00Z',
    status: 'completed',
    category: 'salary',
    affectsDebt: false,
    runningBalance: 1730738671,
  },
];
