import type { CashAccount } from './types.ts';

export const data: CashAccount[] = [
  { 
    systemId: 'ACC_CASH', 
    id: 'cash', 
    name: 'Quỹ tiền mặt', 
    initialBalance: 1727238671, 
    type: 'cash', 
    branchSystemId: 'BRANCH000001',
    isActive: true,
    isDefault: true,
    minBalance: 1000000,
    maxBalance: 5000000000,
  },
  { 
    systemId: 'ACC_VCB', 
    id: 'vcb', 
    name: 'Tài khoản Vietcombank', 
    initialBalance: 500000000, 
    type: 'bank', 
    bankAccountNumber: '0123456789', 
    bankBranch: 'PGD Bến Thành', 
    branchSystemId: 'BRANCH000001',
    isActive: true,
    isDefault: true,
    bankName: 'Vietcombank',
    bankCode: 'VCB',
    accountHolder: 'CÔNG TY TNHH ABC',
    minBalance: 5000000,
  },
  { 
    systemId: 'ACC_ACB', 
    id: 'acb', 
    name: 'Tài khoản ACB', 
    initialBalance: 250000000, 
    type: 'bank', 
    bankAccountNumber: '9876543210', 
    bankBranch: 'Chi nhánh Sài Gòn', 
    branchSystemId: 'BRANCH000002',
    isActive: true,
    isDefault: false,
    bankName: 'ACB',
    bankCode: 'ACB',
    accountHolder: 'CÔNG TY TNHH ABC',
  },
];
