import type { Receipt } from '@/lib/types/prisma-extended';
import { asBusinessId, asSystemId } from '@/lib/id-types';

export const data: Receipt[] = [
  {
    systemId: asSystemId('RECEIPT000001'),
    id: asBusinessId('PT000001'),
    date: '2024-11-10',
    amount: 5_000_000,
    payerTypeSystemId: asSystemId('KHACHHANG'),
    payerTypeName: 'Khách hàng',
    payerName: 'Nguyễn Văn A',
    payerSystemId: asSystemId('CUSTOMER000001'),
    description: 'Thu tiền bán hàng',
    paymentMethodSystemId: asSystemId('TIENMAT'),
    paymentMethodName: 'Tiền mặt',
    accountSystemId: asSystemId('ACC_CASH'),
    paymentReceiptTypeSystemId: asSystemId('RT_SALE'),
    paymentReceiptTypeName: 'Bán hàng',
    branchSystemId: asSystemId('BRANCH000001'),
    branchName: 'Chi nhánh 1',
    createdBy: asSystemId('admin'),
    createdAt: '2024-11-10T10:00:00Z',
    status: 'completed',
    category: 'sale',
    affectsDebt: false,
    runningBalance: 1_732_238_671,
    customerSystemId: asSystemId('CUSTOMER000001'),
    customerName: 'Nguyễn Văn A',
  },
  {
    systemId: asSystemId('RECEIPT000002'),
    id: asBusinessId('PT000002'),
    date: '2024-11-11',
    amount: 3_000_000,
    payerTypeSystemId: asSystemId('KHACHHANG'),
    payerTypeName: 'Khách hàng',
    payerName: 'Trần Thị B',
    payerSystemId: asSystemId('CUSTOMER000002'),
    description: 'Thu tiền khách hàng thanh toán công nợ',
    paymentMethodSystemId: asSystemId('CHUYENKHOAN'),
    paymentMethodName: 'Chuyển khoản',
    accountSystemId: asSystemId('ACC_VCB'),
    paymentReceiptTypeSystemId: asSystemId('RT_PAYMENT'),
    paymentReceiptTypeName: 'Thu công nợ',
    branchSystemId: asSystemId('BRANCH000001'),
    branchName: 'Chi nhánh 1',
    createdBy: asSystemId('admin'),
    createdAt: '2024-11-11T14:30:00Z',
    status: 'completed',
    category: 'customer_payment',
    affectsDebt: true,
    runningBalance: 503_000_000,
    customerSystemId: asSystemId('CUSTOMER000002'),
    customerName: 'Trần Thị B',
  },
];
