import type { Receipt } from './types.ts';
import { asSystemId, asBusinessId } from '../../lib/id-types';

export const data: Receipt[] = [
  {
    systemId: asSystemId('RECEIPT000001'),
    id: asBusinessId('PT000001'),
    date: '2024-11-10',
    amount: 5000000,
    payerTypeSystemId: 'KHACHHANG',
    payerTypeName: 'Khách hàng',
    payerName: 'Nguyễn Văn A',
    payerSystemId: 'CUSTOMER000001',
    description: 'Thu tiền bán hàng',
    paymentMethodSystemId: 'TIENMAT',
    paymentMethodName: 'Tiền mặt',
    accountSystemId: 'ACC_CASH',
    paymentReceiptTypeSystemId: 'RT_SALE',
    paymentReceiptTypeName: 'Bán hàng',
    branchSystemId: 'BRANCH000001',
    branchName: 'Chi nhánh 1',
    createdBy: 'admin',
    createdAt: '2024-11-10T10:00:00Z',
    status: 'completed',
    category: 'sale',
    affectsDebt: false,
    runningBalance: 1732238671,
    customerSystemId: 'CUSTOMER000001',
    customerName: 'Nguyễn Văn A',
  },
  {
    systemId: asSystemId('RECEIPT000002'),
    id: asBusinessId('PT000002'),
    date: '2024-11-11',
    amount: 3000000,
    payerTypeSystemId: 'KHACHHANG',
    payerTypeName: 'Khách hàng',
    payerName: 'Trần Thị B',
    payerSystemId: 'CUSTOMER000002',
    description: 'Thu tiền khách hàng thanh toán công nợ',
    paymentMethodSystemId: 'CHUYENKHOAN',
    paymentMethodName: 'Chuyển khoản',
    accountSystemId: 'ACC_VCB',
    paymentReceiptTypeSystemId: 'RT_PAYMENT',
    paymentReceiptTypeName: 'Thu công nợ',
    branchSystemId: 'BRANCH000001',
    branchName: 'Chi nhánh 1',
    createdBy: 'admin',
    createdAt: '2024-11-11T14:30:00Z',
    status: 'completed',
    category: 'customer_payment',
    affectsDebt: true,
    runningBalance: 503000000,
    customerSystemId: 'CUSTOMER000002',
    customerName: 'Trần Thị B',
  },
];
