import { SHARED_PREVIEW_DATA } from './_shared.preview';

/**
 * Dữ liệu preview cho mẫu in Đơn đổi trả hàng
 * Đồng bộ với: variables/don-doi-tra-hang.ts và templates/sales-return.ts
 */
export const SALES_RETURN_PREVIEW_DATA: Record<string, string> = {
  // Kế thừa dữ liệu chung
  ...SHARED_PREVIEW_DATA,

  // === THÔNG TIN ĐƠN TRẢ HÀNG ===
  '{return_code}': 'TH000444',
  '{order_return_code}': 'TH000444',
  '{order_code}': 'DH000123',
  '{order_qr_code}': '<img src="https://placehold.co/100x100?text=QR" alt="QR" style="width:100px;height:100px"/>',
  '{bar_code(code)}': '<img src="https://placehold.co/150x50?text=BARCODE" alt="Barcode" style="height:50px"/>',
  '{bar_code(reference_number)}': '<img src="https://placehold.co/150x50?text=REF" alt="Ref" style="height:50px"/>',
  '{created_on}': '05/12/2025',
  '{created_on_time}': '14:00',
  '{modified_on}': '05/12/2025',
  '{modified_on_time}': '14:30',
  '{issued_on}': '05/12/2025',
  '{issued_on_time}': '14:00',
  '{source}': 'Tại cửa hàng',
  '{channel}': 'Offline',
  '{reference}': 'REF-TH-001',
  '{tag}': 'Trả hàng',
  '{return_reason}': 'Sản phẩm bị lỗi đường may',
  '{reason_return}': 'Khách đổi size do mua nhầm',

  // === TRẠNG THÁI ===
  '{return_status}': 'Đã hoàn thành',
  '{order_status}': 'Đã hoàn thành',
  '{payment_status}': 'Đã hoàn tiền',
  '{fulfillment_status}': 'Đã nhận hàng',
  '{packed_status}': 'Không áp dụng',
  '{expected_payment_method}': 'Tiền mặt',
  '{expected_delivery_type}': 'Nhận tại cửa hàng',

  // === THÔNG TIN KHÁCH HÀNG ===
  '{customer_code}': 'KH00456',
  '{customer_name}': 'Nguyễn Văn A',
  '{customer_contact}': 'Nguyễn Văn A',
  '{customer_phone_number}': '0912 345 678',
  '{customer_email}': 'nguyenvana@email.com',
  '{customer_address}': '456 Lê Duẩn, Đà Nẵng',
  '{customer_point}': '1,500',
  '{customer_card}': 'Thẻ Vàng',
  '{customer_tax_number}': '0123456789',
  '{billing_address}': '456 Lê Duẩn, Đà Nẵng',
  '{shipping_address}': '456 Lê Duẩn, Quận Hải Châu, Đà Nẵng',
  '{shipping_address:full_name}': 'Nguyễn Văn A',
  '{shipping_address:phone_number}': '0912 345 678',
  '{ship_on_min}': '05/12/2025',
  '{ship_on_max}': '05/12/2025',
  '{price_list_name}': 'Bảng giá lẻ',
  '{currency_name}': 'VND',

  // === NỢ KHÁCH HÀNG ===
  '{customer_debt}': '1,750,000',
  '{customer_debt_text}': 'Một triệu bảy trăm năm mươi nghìn đồng',
  '{customer_debt_prev}': '2,000,000',
  '{customer_debt_prev_text}': 'Hai triệu đồng',

  // === THÔNG TIN SẢN PHẨM TRẢ ===
  '{line_stt}': '1',
  '{line_variant_code}': 'ATP-L-XANH',
  '{line_product_name}': 'Áo thun Polo nam',
  '{line_variant}': 'Size L - Màu xanh',
  '{line_variant_barcode}': '8935123456790',
  '{line_variant_options}': 'Size: L, Màu: Xanh',
  '{line_unit}': 'Cái',
  '{line_quantity}': '1',
  '{line_price}': '250,000',
  '{line_price_after_discount}': '250,000',
  '{line_discount_rate}': '0%',
  '{line_discount_amount}': '0',
  '{line_tax_rate}': '0%',
  '{line_tax_amount}': '0',
  '{line_tax_included}': 'Không',
  '{line_tax_exclude}': '250,000',
  '{line_amount}': '250,000',
  '{line_total}': '250,000',
  '{line_amount_none_discount}': '250,000',
  '{line_note}': 'Sản phẩm bị lỗi đường may',
  '{line_brand}': 'TrendTech',
  '{line_category}': 'Áo thun nam',
  '{line_promotion_or_loyalty}': '',
  '{total_line_item_discount}': '0',
  '{serials}': 'SN123456',
  '{lots_number_code1}': '',
  '{lots_number_code2}': '',
  '{lots_number_code3}': '',
  '{lots_number_code4}': '',

  // === THÔNG TIN SẢN PHẨM TRẢ (alias) ===
  '{return_line_stt}': '1',
  '{return_line_variant_code}': 'ATP-L-XANH',
  '{return_line_product_name}': 'Áo thun Polo nam',
  '{return_line_variant}': 'Size L - Màu xanh',
  '{return_line_unit}': 'Cái',
  '{return_line_quantity}': '1',
  '{return_line_price}': '250,000',
  '{return_line_amount}': '250,000',
  '{return_line_note}': 'Sản phẩm bị lỗi đường may',
  '{return_serials}': 'SN123456',

  // === TỔNG GIÁ TRỊ ===
  '{total_quantity}': '1',
  '{return_total_quantity}': '1',
  '{total}': '250,000',
  '{total_order}': '250,000',
  '{total_none_discount}': '250,000',
  '{total_discount}': '0',
  '{product_discount}': '0',
  '{order_discount}': '0',
  '{order_discount_rate}': '0%',
  '{order_discount_value}': '0',
  '{total_tax}': '0',
  '{total_extra_tax}': '0',
  '{total_tax_included_line}': '0',
  '{total_amount_before_tax}': '250,000',
  '{total_amount_after_tax}': '250,000',
  '{delivery_fee}': '0',
  '{total_amount}': '250,000',
  '{return_total_amount}': '250,000',
  '{refund_amount}': '250,000',
  '{total_order_exchange_amount}': '0',
  '{total_text}': 'Hai trăm năm mươi nghìn đồng',
  '{total_remain}': '0',
  '{money_return}': '0',
  '{payment_customer}': '0',
  '{payment_name}': 'Tiền mặt',
  '{order_exchange_payment_note}': 'Đổi hàng tương đương',
  '{promotion_name}': '',
  '{promotion_code}': '',
  '{order_note}': 'Khách đổi size do mua nhầm',
  '{note}': 'Khách đổi size do mua nhầm',

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  '{refund_status}': 'Đã hoàn tiền',
  '{account_name}': 'Trần Văn B',
};
