import * as React from "react";
import { useSupplierStore } from "../store.ts";
import { useToast } from "../../../hooks/use-toast.ts";
import { useProvinceStore } from "../../settings/provinces/store.ts";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../../../components/ui/dialog.tsx";
import { Button } from "../../../components/ui/button.tsx";
import { Input } from "../../../components/ui/input.tsx";
import { Label } from "../../../components/ui/label.tsx";
import { VirtualizedCombobox } from "../../../components/ui/virtualized-combobox.tsx";

interface QuickAddSupplierDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: (supplierId: string) => void;
}

export function QuickAddSupplierDialog({
  open,
  onOpenChange,
  onSuccess,
}: QuickAddSupplierDialogProps) {
  const { add } = useSupplierStore();
  const { data: provinces, getWardsByProvinceId } = useProvinceStore();
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = React.useState(false);

  // Form state
  const [formData, setFormData] = React.useState({
    name: "",
    phone: "",
    email: "",
    address: "",
    city: "",
    district: "",
  });

  // Validation errors
  const [errors, setErrors] = React.useState<Record<string, string>>({});

  // Auto-focus first input when dialog opens
  const nameInputRef = React.useRef<HTMLInputElement>(null);
  React.useEffect(() => {
    if (open) {
      setTimeout(() => nameInputRef.current?.focus(), 100);
    }
  }, [open]);

  // Reset form when dialog closes
  React.useEffect(() => {
    if (!open) {
      setFormData({
        name: "",
        phone: "",
        email: "",
        address: "",
        city: "",
        district: "",
      });
      setErrors({});
      setIsSubmitting(false);
    }
  }, [open]);

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.name.trim()) {
      newErrors.name = "Tên nhà cung cấp là bắt buộc";
    }

    if (formData.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      newErrors.email = "Email không hợp lệ";
    }

    if (formData.phone && !/^[0-9]{10,11}$/.test(formData.phone.replace(/\s/g, ""))) {
      newErrors.phone = "Số điện thoại không hợp lệ (10-11 số)";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Prepare combobox options
  const provinceOptions = React.useMemo(
    () => provinces.map((p) => ({ value: p.name, label: p.name })),
    [provinces]
  );

  // Find selected province
  const selectedProvince = React.useMemo(
    () => provinces.find((p) => p.name === formData.city),
    [provinces, formData.city]
  );

  // Get wards for selected province
  const availableWards = React.useMemo(
    () => (selectedProvince ? getWardsByProvinceId(selectedProvince.id) : []),
    [selectedProvince, getWardsByProvinceId]
  );

  const wardOptions = React.useMemo(
    () => availableWards.map((w) => ({ value: w.name, label: w.name })),
    [availableWards]
  );

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setIsSubmitting(true);

    try {
      const newSupplier = {
        id: "", // Will be auto-generated by store
        name: formData.name.trim(),
        phone: formData.phone.trim(),
        email: formData.email.trim(),
        address: formData.address.trim() + (formData.city ? `, ${formData.city}` : "") + (formData.district ? `, ${formData.district}` : ""),
        taxCode: "",
        accountManager: "",
        status: "Đang Giao Dịch" as const,
      };

      const addedSupplier = add(newSupplier);

      toast({
        title: "Thành công",
        description: `Đã thêm nhà cung cấp "${newSupplier.name}"`,
      });

      onOpenChange(false);
      
      // Call success callback with new supplier systemId
      if (onSuccess && addedSupplier) {
        onSuccess(addedSupplier.systemId);
      }
    } catch (error) {
      toast({
        title: "Lỗi",
        description: "Không thể thêm nhà cung cấp. Vui lòng thử lại.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Thêm mới nhà cung cấp</DialogTitle>
          <DialogDescription>
            Nhập thông tin nhà cung cấp mới. Các trường có dấu * là bắt buộc.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Tên nhà cung cấp */}
          <div className="space-y-2">
            <Label htmlFor="supplier-name">
              Tên nhà cung cấp <span className="text-destructive">*</span>
            </Label>
            <Input
              id="supplier-name"
              ref={nameInputRef}
              placeholder="Nhập họ tên"
              value={formData.name}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, name: e.target.value }))
              }
              className={errors.name ? "border-destructive" : ""}
            />
            {errors.name && (
              <p className="text-sm text-destructive">{errors.name}</p>
            )}
          </div>

          {/* Row 1: Phone + Email */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="supplier-phone">Số điện thoại</Label>
              <Input
                id="supplier-phone"
                placeholder="Nhập số điện thoại"
                value={formData.phone}
                onChange={(e) =>
                  setFormData((prev) => ({ ...prev, phone: e.target.value }))
                }
                className={errors.phone ? "border-destructive" : ""}
              />
              {errors.phone && (
                <p className="text-sm text-destructive">{errors.phone}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="supplier-email">Email</Label>
              <Input
                id="supplier-email"
                type="email"
                placeholder="Nhập email"
                value={formData.email}
                onChange={(e) =>
                  setFormData((prev) => ({ ...prev, email: e.target.value }))
                }
                className={errors.email ? "border-destructive" : ""}
              />
              {errors.email && (
                <p className="text-sm text-destructive">{errors.email}</p>
              )}
            </div>
          </div>

          {/* Địa chỉ chi tiết */}
          <div className="space-y-2">
            <Label htmlFor="supplier-address">Địa chỉ chi tiết</Label>
            <Input
              id="supplier-address"
              placeholder="Nhập số nhà, tên đường, tên khu vực"
              value={formData.address}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, address: e.target.value }))
              }
            />
          </div>

          {/* Row 2: City + District */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="supplier-city">Tỉnh/Thành phố</Label>
              <VirtualizedCombobox
                options={provinceOptions}
                value={
                  formData.city
                    ? { value: formData.city, label: formData.city }
                    : null
                }
                onChange={(option) => {
                  setFormData((prev) => ({
                    ...prev,
                    city: option?.value || "",
                    district: "", // Reset district when province changes
                  }));
                }}
                placeholder="Chọn Tỉnh/Thành phố"
                searchPlaceholder="Tìm tỉnh/thành phố..."
                emptyPlaceholder="Không tìm thấy"
                estimatedItemHeight={36}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="supplier-district">Phường/Xã</Label>
              <VirtualizedCombobox
                options={wardOptions}
                value={
                  formData.district
                    ? { value: formData.district, label: formData.district }
                    : null
                }
                onChange={(option) => {
                  setFormData((prev) => ({
                    ...prev,
                    district: option?.value || "",
                  }));
                }}
                placeholder={selectedProvince ? "Chọn Phường/Xã" : "Chọn tỉnh trước"}
                searchPlaceholder="Tìm phường/xã..."
                emptyPlaceholder="Không tìm thấy"
                disabled={!selectedProvince}
                estimatedItemHeight={36}
              />
            </div>
          </div>

          <DialogFooter className="gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isSubmitting}
            >
              Thoát
            </Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? "Đang thêm..." : "Thêm"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
