import { asSystemId, asBusinessId } from '../../../lib/id-types';
import type { CustomerSource } from './types';

export const defaultCustomerSources: CustomerSource[] = [
  {
    systemId: asSystemId('CSOURCE00000001'),
    id: asBusinessId('WEBSITE'),
    name: 'Website',
    description: 'Khách hàng đến từ website công ty',
    type: 'Online',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: asSystemId('CSOURCE00000002'),
    id: asBusinessId('FACEBOOK'),
    name: 'Facebook',
    description: 'Khách hàng từ quảng cáo Facebook',
    type: 'Online',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: asSystemId('CSOURCE00000003'),
    id: asBusinessId('ZALO'),
    name: 'Zalo',
    description: 'Khách hàng từ Zalo',
    type: 'Online',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: asSystemId('CSOURCE00000004'),
    id: asBusinessId('GIOITHIEU'),
    name: 'Giới thiệu',
    description: 'Khách hàng được giới thiệu bởi khách cũ',
    type: 'Referral',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: asSystemId('CSOURCE00000005'),
    id: asBusinessId('CUAHANG'),
    name: 'Cửa hàng',
    description: 'Khách hàng đến trực tiếp cửa hàng',
    type: 'Offline',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: asSystemId('CSOURCE00000006'),
    id: asBusinessId('DOITAC'),
    name: 'Đối tác',
    description: 'Khách hàng từ đối tác liên kết',
    type: 'Other',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
