import type { CustomerSource } from './types';

export const defaultCustomerSources: CustomerSource[] = [
  {
    systemId: 'CSOURCE00000001',
    id: 'WEBSITE',
    name: 'Website',
    description: 'Khách hàng đến từ website công ty',
    type: 'Online',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'CSOURCE00000002',
    id: 'FACEBOOK',
    name: 'Facebook',
    description: 'Khách hàng từ quảng cáo Facebook',
    type: 'Online',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'CSOURCE00000003',
    id: 'ZALO',
    name: 'Zalo',
    description: 'Khách hàng từ Zalo',
    type: 'Online',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'CSOURCE00000004',
    id: 'GIOITHIEU',
    name: 'Giới thiệu',
    description: 'Khách hàng được giới thiệu bởi khách cũ',
    type: 'Referral',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'CSOURCE00000005',
    id: 'CUAHANG',
    name: 'Cửa hàng',
    description: 'Khách hàng đến trực tiếp cửa hàng',
    type: 'Offline',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'CSOURCE00000006',
    id: 'DOITAC',
    name: 'Đối tác',
    description: 'Khách hàng từ đối tác liên kết',
    type: 'Other',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
