import { asSystemId, asBusinessId } from '../../../lib/id-types';
import type { PaymentTerm } from './types';
import { buildSeedAuditFields } from '@/lib/seed-audit';

export const defaultPaymentTerms: PaymentTerm[] = [
  {
    systemId: asSystemId('PTERM00000001'),
    id: asBusinessId('COD'),
    name: 'Thanh toán ngay (COD)',
    description: 'Thanh toán khi nhận hàng',
    days: 0,
    isDefault: true,
    isActive: true,
     ...buildSeedAuditFields({ createdAt: '2024-01-19T08:00:00Z' }),
  },
  {
    systemId: asSystemId('PTERM00000002'),
    id: asBusinessId('NET7'),
    name: 'Thanh toán trong 7 ngày',
    description: 'Thanh toán trong vòng 7 ngày kể từ ngày nhận hàng',
    days: 7,
    isDefault: false,
    isActive: true,
     ...buildSeedAuditFields({ createdAt: '2024-01-20T08:00:00Z' }),
  },
  {
    systemId: asSystemId('PTERM00000003'),
    id: asBusinessId('NET15'),
    name: 'Thanh toán trong 15 ngày',
    description: 'Thanh toán trong vòng 15 ngày kể từ ngày nhận hàng',
    days: 15,
    isDefault: false,
    isActive: true,
     ...buildSeedAuditFields({ createdAt: '2024-01-21T08:00:00Z' }),
  },
  {
    systemId: asSystemId('PTERM00000004'),
    id: asBusinessId('NET30'),
    name: 'Thanh toán trong 30 ngày',
    description: 'Thanh toán trong vòng 30 ngày kể từ ngày nhận hàng',
    days: 30,
    isDefault: false,
    isActive: true,
     ...buildSeedAuditFields({ createdAt: '2024-01-22T08:00:00Z' }),
  },
  {
    systemId: asSystemId('PTERM00000005'),
    id: asBusinessId('NET60'),
    name: 'Thanh toán trong 60 ngày',
    description: 'Thanh toán trong vòng 60 ngày kể từ ngày nhận hàng',
    days: 60,
    isDefault: false,
    isActive: true,
     ...buildSeedAuditFields({ createdAt: '2024-01-23T08:00:00Z' }),
  },
  {
    systemId: asSystemId('PTERM00000006'),
    id: asBusinessId('NET90'),
    name: 'Thanh toán trong 90 ngày',
    description: 'Thanh toán trong vòng 90 ngày kể từ ngày nhận hàng',
    days: 90,
    isDefault: false,
    isActive: true,
     ...buildSeedAuditFields({ createdAt: '2024-01-24T08:00:00Z' }),
  },
];
