import type { PaymentTerm } from './types';

export const defaultPaymentTerms: PaymentTerm[] = [
  {
    systemId: 'PTERM00000001',
    id: 'COD',
    name: 'Thanh toán ngay (COD)',
    description: 'Thanh toán khi nhận hàng',
    days: 0,
    isDefault: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'PTERM00000002',
    id: 'NET7',
    name: 'Thanh toán trong 7 ngày',
    description: 'Thanh toán trong vòng 7 ngày kể từ ngày nhận hàng',
    days: 7,
    isDefault: false,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'PTERM00000003',
    id: 'NET15',
    name: 'Thanh toán trong 15 ngày',
    description: 'Thanh toán trong vòng 15 ngày kể từ ngày nhận hàng',
    days: 15,
    isDefault: false,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'PTERM00000004',
    id: 'NET30',
    name: 'Thanh toán trong 30 ngày',
    description: 'Thanh toán trong vòng 30 ngày kể từ ngày nhận hàng',
    days: 30,
    isDefault: false,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'PTERM00000005',
    id: 'NET60',
    name: 'Thanh toán trong 60 ngày',
    description: 'Thanh toán trong vòng 60 ngày kể từ ngày nhận hàng',
    days: 60,
    isDefault: false,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    systemId: 'PTERM00000006',
    id: 'NET90',
    name: 'Thanh toán trong 90 ngày',
    description: 'Thanh toán trong vòng 90 ngày kể từ ngày nhận hàng',
    days: 90,
    isDefault: false,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
