import type { SalesReturn } from './types.ts';
import { asSystemId, asBusinessId } from '../../lib/id-types.ts';

const SEED_AUTHOR = asSystemId('EMP000001');
const buildAuditFields = (createdAt: string, createdBy = SEED_AUTHOR) => ({
  createdAt,
  updatedAt: createdAt,
  createdBy,
  updatedBy: createdBy,
});

export const data: SalesReturn[] = [
  // Phiếu trả hàng đã hoàn tất - Hoàn tiền
  {
    systemId: asSystemId('RETURN000001'),
    id: asBusinessId('TH000001'),
    orderSystemId: asSystemId('ORDER000001'),
    orderId: asBusinessId('DH000001'),
    customerSystemId: asSystemId('CUST000001'),
    customerName: 'Công ty Cổ phần Bất động sản Hưng Thịnh',
    branchSystemId: asSystemId('BRANCH000003'),
    branchName: 'Chi nhánh Trung tâm',
    returnDate: '2025-11-10 09:30',
    reason: 'Sản phẩm lỗi kỹ thuật',
    note: 'Chuột bị lỗi nút click, khách yêu cầu hoàn tiền',
    notes: 'Đã kiểm tra và xác nhận lỗi từ nhà sản xuất',
    items: [
      {
        productSystemId: asSystemId('PRODUCT000002'),
        productId: asBusinessId('SP000002'),
        productName: 'Chuột Logitech MX Master 3',
        returnQuantity: 1,
        unitPrice: 2000000,
        totalValue: 2000000,
        note: 'Lỗi nút click trái',
      },
    ],
    totalReturnValue: 2000000,
    isReceived: true,
    exchangeItems: [],
    subtotalNew: 0,
    shippingFeeNew: 0,
    grandTotalNew: 0,
    finalAmount: -2000000,
    refundMethod: 'Tiền mặt',
    refundAmount: 2000000,
    accountSystemId: asSystemId('ACC000001'),
    creatorSystemId: SEED_AUTHOR,
    creatorName: 'Nguyễn Văn A',
    ...buildAuditFields('2025-11-10T09:30:00Z'),
  },
  // Phiếu trả hàng - Đổi hàng
  {
    systemId: asSystemId('RETURN000002'),
    id: asBusinessId('TH000002'),
    orderSystemId: asSystemId('ORDER000003'),
    orderId: asBusinessId('DH000003'),
    customerSystemId: asSystemId('CUST000003'),
    customerName: 'Anh Trần Minh Hoàng',
    branchSystemId: asSystemId('BRANCH000003'),
    branchName: 'Chi nhánh Trung tâm',
    returnDate: '2025-11-15 14:00',
    reason: 'Đổi sang sản phẩm khác',
    note: 'Khách muốn đổi iPad Air sang iPad Pro',
    items: [
      {
        productSystemId: asSystemId('PRODUCT000005'),
        productId: asBusinessId('SP000005'),
        productName: 'Máy tính bảng iPad Air',
        returnQuantity: 1,
        unitPrice: 18000000,
        totalValue: 18000000,
        note: 'Đổi lên model cao hơn',
      },
    ],
    totalReturnValue: 18000000,
    isReceived: true,
    exchangeItems: [
      {
        productSystemId: asSystemId('PRODUCT000011'),
        productId: asBusinessId('SP000011'),
        productName: 'Máy tính bảng iPad Pro 12.9"',
        quantity: 1,
        unitPrice: 28000000,
        discount: 0,
        discountType: 'fixed',
      },
    ],
    subtotalNew: 28000000,
    shippingFeeNew: 0,
    grandTotalNew: 28000000,
    finalAmount: 10000000,
    payments: [
      {
        method: 'Chuyển khoản',
        accountSystemId: asSystemId('ACC000002'),
        amount: 10000000,
      },
    ],
    creatorSystemId: asSystemId('EMP000002'),
    creatorName: 'Trần Thị B',
    ...buildAuditFields('2025-11-15T14:00:00Z'),
  },
  // Phiếu trả hàng - Chưa nhận hàng
  {
    systemId: asSystemId('RETURN000003'),
    id: asBusinessId('TH000003'),
    orderSystemId: asSystemId('ORDER000006'),
    orderId: asBusinessId('DH000006'),
    customerSystemId: asSystemId('CUST000005'),
    customerName: 'Chị Nguyễn Thị Hương',
    branchSystemId: asSystemId('BRANCH000003'),
    branchName: 'Chi nhánh Trung tâm',
    returnDate: '2025-12-05 11:00',
    reason: 'Sản phẩm không đúng mô tả',
    note: 'Khách phản ánh màu sắc laptop không đúng như hình',
    items: [
      {
        productSystemId: asSystemId('PRODUCT000001'),
        productId: asBusinessId('SP000001'),
        productName: 'Laptop Dell Inspiron 15',
        returnQuantity: 1,
        unitPrice: 15000000,
        totalValue: 15000000,
        note: 'Khách muốn đổi màu bạc sang màu đen',
      },
    ],
    totalReturnValue: 15000000,
    isReceived: false,
    exchangeItems: [],
    subtotalNew: 0,
    shippingFeeNew: 0,
    grandTotalNew: 0,
    finalAmount: -15000000,
    deliveryMethod: 'Dịch vụ giao hàng',
    shippingPartnerId: 'GHN',
    creatorSystemId: asSystemId('EMP000003'),
    creatorName: 'Phạm Văn D',
    ...buildAuditFields('2025-12-05T11:00:00Z'),
  },
  // Phiếu trả hàng - Hoàn tiền một phần
  {
    systemId: asSystemId('RETURN000004'),
    id: asBusinessId('TH000004'),
    orderSystemId: asSystemId('ORDER000007'),
    orderId: asBusinessId('DH000007'),
    customerSystemId: asSystemId('CUST000006'),
    customerName: 'Anh Phạm Văn Tùng',
    branchSystemId: asSystemId('BRANCH000003'),
    branchName: 'Chi nhánh Trung tâm',
    returnDate: '2025-12-07 16:30',
    reason: 'Trả một phần đơn hàng',
    note: 'Khách chỉ giữ lại chuột, trả webcam',
    items: [
      {
        productSystemId: asSystemId('PRODUCT000009'),
        productId: asBusinessId('SP000009'),
        productName: 'Webcam Logitech C920',
        returnQuantity: 1,
        unitPrice: 1200000,
        totalValue: 1200000,
        note: 'Không cần dùng webcam',
      },
    ],
    totalReturnValue: 1200000,
    isReceived: true,
    exchangeItems: [],
    subtotalNew: 0,
    shippingFeeNew: 0,
    grandTotalNew: 0,
    finalAmount: -1200000,
    refunds: [
      {
        method: 'Tiền mặt',
        accountSystemId: asSystemId('ACC000001'),
        amount: 1200000,
      },
    ],
    creatorSystemId: asSystemId('EMP000004'),
    creatorName: 'Võ Thị F',
    ...buildAuditFields('2025-12-07T16:30:00Z'),
  },
  // Phiếu trả hàng - Đổi + Hoàn tiền chênh lệch
  {
    systemId: asSystemId('RETURN000005'),
    id: asBusinessId('TH000005'),
    orderSystemId: asSystemId('ORDER000010'),
    orderId: asBusinessId('DH000010'),
    customerSystemId: asSystemId('CUST000009'),
    customerName: 'Anh Đỗ Văn Hùng',
    branchSystemId: asSystemId('BRANCH000003'),
    branchName: 'Chi nhánh Trung tâm',
    returnDate: '2025-12-09 10:00',
    reason: 'Đổi sang model cũ hơn',
    note: 'Khách muốn đổi AirPods Pro sang AirPods 3, lấy lại tiền chênh lệch',
    items: [
      {
        productSystemId: asSystemId('PRODUCT000004'),
        productId: asBusinessId('SP000004'),
        productName: 'Tai nghe AirPods Pro',
        returnQuantity: 1,
        unitPrice: 5000000,
        totalValue: 5000000,
        note: 'Đổi xuống model thấp hơn',
      },
    ],
    totalReturnValue: 5000000,
    isReceived: true,
    exchangeItems: [
      {
        productSystemId: asSystemId('PRODUCT000012'),
        productId: asBusinessId('SP000012'),
        productName: 'Tai nghe AirPods 3',
        quantity: 1,
        unitPrice: 4000000,
        discount: 0,
        discountType: 'fixed',
      },
    ],
    subtotalNew: 4000000,
    shippingFeeNew: 0,
    grandTotalNew: 4000000,
    finalAmount: -1000000,
    refunds: [
      {
        method: 'Tiền mặt',
        accountSystemId: asSystemId('ACC000001'),
        amount: 1000000,
      },
    ],
    creatorSystemId: SEED_AUTHOR,
    creatorName: 'Nguyễn Văn A',
    ...buildAuditFields('2025-12-09T10:00:00Z'),
  },
];

// Reminder constant để giữ `createdAt/createdBy` trong file, tránh quên audit metadata khi bổ sung seed thật.
const __salesReturnMetadataReminder: Array<keyof SalesReturn> = ['createdAt', 'createdBy'];
void __salesReturnMetadataReminder;
