import { TemplateVariable } from '../types';

export const DON_NHAP_HANG_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_fax}', label: 'Số Fax', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  // Thông tin đơn nhập
  { key: '{purchase_order_code}', label: 'Mã đơn nhập', group: 'Thông tin đơn nhập' },
  { key: '{modified_on}', label: 'Ngày cập nhật', group: 'Thông tin đơn nhập' },
  { key: '{received_on}', label: 'Ngày nhận', group: 'Thông tin đơn nhập' },
  { key: '{received_on_time}', label: 'Thời gian nhận', group: 'Thông tin đơn nhập' },
  { key: '{due_on}', label: 'Ngày hẹn giao', group: 'Thông tin đơn nhập' },
  { key: '{supplier_name}', label: 'Tên NCC', group: 'Thông tin đơn nhập' },
  { key: '{supplier_code}', label: 'Mã NCC', group: 'Thông tin đơn nhập' },
  { key: '{supplier_phone}', label: 'SĐT NCC', group: 'Thông tin đơn nhập' },
  { key: '{supplier_email}', label: 'Email NCC', group: 'Thông tin đơn nhập' },
  { key: '{supplier_address}', label: 'Địa chỉ NCC', group: 'Thông tin đơn nhập' },
  { key: '{billing_address}', label: 'Địa chỉ giao hóa đơn', group: 'Thông tin đơn nhập' },
  { key: '{supplier_debt_text}', label: 'Nợ NCC bằng chữ', group: 'Thông tin đơn nhập' },
  { key: '{supplier_debt_prev_text}', label: 'Nợ cũ NCC bằng chữ', group: 'Thông tin đơn nhập' },
  { key: '{weight_g}', label: 'Tổng khối lượng đơn nhập hàng (g)', group: 'Thông tin đơn nhập' },
  { key: '{weight_kg}', label: 'Tổng khối lượng đơn nhập hàng (kg)', group: 'Thông tin đơn nhập' },
  { key: '{tags}', label: 'Tags', group: 'Thông tin đơn nhập' },
  { key: '{total_transaction_amount}', label: 'Tổng tiền đã thanh toán', group: 'Thông tin đơn nhập' },
  { key: '{total_remain}', label: 'Tổng tiền còn phải trả', group: 'Thông tin đơn nhập' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin đơn nhập' },
  { key: '{modified_on_time}', label: 'Thời gian cập nhật', group: 'Thông tin đơn nhập' },
  { key: '{reference}', label: 'Tham chiếu', group: 'Thông tin đơn nhập' },
  { key: '{created_on_time}', label: 'Thời gian tạo', group: 'Thông tin đơn nhập' },
  { key: '{due_on_time}', label: 'Thời gian hẹn giao', group: 'Thông tin đơn nhập' },
  { key: '{status}', label: 'Trạng thái', group: 'Thông tin đơn nhập' },
  { key: '{received_status}', label: 'Trạng thái nhập kho', group: 'Thông tin đơn nhập' },
  { key: '{financial_status}', label: 'Trạng thái thanh toán', group: 'Thông tin đơn nhập' },
  { key: '{refund_status}', label: 'Trạng thái hoàn hàng', group: 'Thông tin đơn nhập' },
  { key: '{refund_transaction_status}', label: 'Trạng thái hoàn tiền', group: 'Thông tin đơn nhập' },
  { key: '{supplier_debt}', label: 'Nợ nhà cung cấp', group: 'Thông tin đơn nhập' },
  { key: '{supplier_debt_prev}', label: 'Nợ cũ NCC', group: 'Thông tin đơn nhập' },
  { key: '{account_name}', label: 'Nhân viên tạo', group: 'Thông tin đơn nhập' },
  { key: '{assignee_name}', label: 'Nhân viên phụ trách NCC', group: 'Thông tin đơn nhập' },
  { key: '{note}', label: 'Ghi chú', group: 'Thông tin đơn nhập' },
  // Thông tin sản phẩm
  { key: '{line_stt}', label: 'STT', group: 'Thông tin sản phẩm' },
  { key: '{line_unit}', label: 'Đơn vị tính', group: 'Thông tin sản phẩm' },
  { key: '{line_discount_rate}', label: 'Chiết khấu sản phẩm %', group: 'Thông tin sản phẩm' },
  { key: '{line_note}', label: 'Ghi chú sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_barcode}', label: 'Mã Barcode', group: 'Thông tin sản phẩm' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_options}', label: 'Thuộc tính sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_brand}', label: 'Thương hiệu sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_tax_rate}', label: 'Thuế (%)', group: 'Thông tin sản phẩm' },
  { key: '{line_weight_kg}', label: 'Tổng khối lượng sản phẩm (kg)', group: 'Thông tin sản phẩm' },
  { key: '{lots_number_code1}', label: 'Mã lô sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{lots_number_code3}', label: 'Mã lô - NSX - NHH sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_tax_exclude}', label: 'Giá chưa bao gồm thuế', group: 'Thông tin sản phẩm' },
  { key: '{line_price_after_discount}', label: 'Giá nhập sau chiết khấu', group: 'Thông tin sản phẩm' },
  { key: '{line_title}', label: 'Tên hàng', group: 'Thông tin sản phẩm' },
  { key: '{line_tax}', label: 'Loại thuế theo từng mặt hàng', group: 'Thông tin sản phẩm' },
  { key: '{line_discount_amount}', label: 'Chiết khấu sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_price}', label: 'Giá nhập', group: 'Thông tin sản phẩm' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_code}', label: 'Mã phiên bản sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_name}', label: 'Tên phiên bản sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_category}', label: 'Loại sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_tax_amount}', label: 'Thuế (giá trị)', group: 'Thông tin sản phẩm' },
  { key: '{serials}', label: 'Serial', group: 'Thông tin sản phẩm' },
  { key: '{line_weight_g}', label: 'Tổng khối lượng sản phẩm (g)', group: 'Thông tin sản phẩm' },
  { key: '{lots_number_code2}', label: 'Mã lô - Số lượng bán sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{lots_number_code4}', label: 'Mã lô - NSX - NHH - Số lượng bán sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_tax_included}', label: 'Giá đã bao gồm thuế', group: 'Thông tin sản phẩm' },
  // Tổng giá trị
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng giá trị' },
  { key: '{total_amount_transaction}', label: 'Tổng tiền trả lại', group: 'Tổng giá trị' },
  { key: '{total_discounts_value}', label: 'Chiết khấu đơn nhập (giá trị)', group: 'Tổng giá trị' },
  { key: '{total_amount_text}', label: 'Tổng tiền bằng chữ', group: 'Tổng giá trị' },
  { key: '{total_landed_costs}', label: 'Tổng chi phí', group: 'Tổng giá trị' },
  { key: '{total_amount_before_tax}', label: 'Tổng tiền trước thuế', group: 'Tổng giá trị' },
  { key: '{payments}', label: 'Tên phương thức thanh toán: Số tiền thanh toán', group: 'Tổng giá trị' },
  { key: '{product_discount}', label: 'Chiết khấu sản phẩm', group: 'Tổng giá trị' },
  { key: '{total_price}', label: 'Tổng tiền', group: 'Tổng giá trị' },
  { key: '{total}', label: 'Tổng tiền hàng', group: 'Tổng giá trị' },
  { key: '{total_discounts_rate}', label: 'Chiết khấu đơn nhập (%)', group: 'Tổng giá trị' },
  { key: '{total_discounts}', label: 'Chiết khấu đơn nhập', group: 'Tổng giá trị' },
  { key: '{total_extra_tax}', label: 'Tổng thuế phải trả thêm', group: 'Tổng giá trị' },
  { key: '{total_tax_included_line}', label: 'Tổng thuế đã bao gồm trong sản phẩm', group: 'Tổng giá trị' },
  { key: '{total_amount_after_tax}', label: 'Tổng tiền sau thuế', group: 'Tổng giá trị' },
];

