import { TemplateVariable } from '../types';

export const DON_DAT_HANG_NHAP_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_fax}', label: 'Số Fax', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  // Thông tin đơn đặt hàng nhập
  { key: '{order_supplier_code}', label: 'Mã đơn', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{status}', label: 'Trạng thái', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{due_on}', label: 'Ngày nhập dự kiến', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{completed_on}', label: 'Ngày hoàn thành', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{ended_on}', label: 'Ngày kết thúc', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{cancelled_on}', label: 'Ngày hủy', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_name}', label: 'Tên NCC', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_code}', label: 'Mã NCC', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_phone}', label: 'SĐT NCC', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_email}', label: 'Email NCC', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_address}', label: 'Địa chỉ NCC', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_debt}', label: 'Nợ nhà cung cấp', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_debt_prev}', label: 'Nợ cũ nhà cung cấp', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_debt_text}', label: 'Nợ NCC bằng chữ', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{supplier_debt_prev_text}', label: 'Nợ cũ NCC bằng chữ', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{activated_account_name}', label: 'Nhân viên tạo đơn', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{assignee_name}', label: 'Nhân viên phụ trách NCC', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{weight_kg}', label: 'Tổng khối lượng đơn nhập hàng (kg)', group: 'Thông tin đơn đặt hàng nhập' },
  { key: '{weight_g}', label: 'Tổng khối lượng đơn nhập hàng (g)', group: 'Thông tin đơn đặt hàng nhập' },
  // Thông tin sản phẩm
  { key: '{line_stt}', label: 'STT', group: 'Thông tin sản phẩm' },
  { key: '{line_title}', label: 'Tên hàng', group: 'Thông tin sản phẩm' },
  { key: '{line_unit}', label: 'Đơn vị tính', group: 'Thông tin sản phẩm' },
  { key: '{line_note}', label: 'Ghi chú sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_quantity}', label: 'Số lượng đặt', group: 'Thông tin sản phẩm' },
  { key: '{line_received_quantity}', label: 'Số lượng nhập', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_code}', label: 'Mã phiên bản sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_name}', label: 'Tên phiên bản sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_barcode}', label: 'Mã Barcode', group: 'Thông tin sản phẩm' },
  { key: '{line_category}', label: 'Loại sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_price}', label: 'Giá nhập', group: 'Thông tin sản phẩm' },
  { key: '{line_price_after_discount}', label: 'Giá nhập sau chiết khấu', group: 'Thông tin sản phẩm' },
  { key: '{line_discount_amount}', label: 'Chiết khấu sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Thông tin sản phẩm' },
  { key: '{line_tax_exclude}', label: 'Giá chưa bao gồm thuế', group: 'Thông tin sản phẩm' },
  { key: '{line_tax_included}', label: 'Giá đã bao gồm thuế', group: 'Thông tin sản phẩm' },
  { key: '{line_tax_amount}', label: 'Thuế (giá trị)', group: 'Thông tin sản phẩm' },
  { key: '{line_weight_g}', label: 'Tổng khối lượng sản phẩm (g)', group: 'Thông tin sản phẩm' },
  { key: '{line_weight_kg}', label: 'Tổng khối lượng sản phẩm (kg)', group: 'Thông tin sản phẩm' },
  { key: '{line_discount_rate}', label: 'Chiết khấu sản phẩm %', group: 'Thông tin sản phẩm' },
  // Tổng giá trị
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng giá trị' },
  { key: '{total_line_amount_text}', label: 'Tổng tiền bằng chữ', group: 'Tổng giá trị' },
  { key: '{total_price}', label: 'Tổng tiền', group: 'Tổng giá trị' },
  { key: '{total_line_amount}', label: 'Tổng tiền hàng', group: 'Tổng giá trị' },
  { key: '{note}', label: 'Ghi chú', group: 'Tổng giá trị' },
  { key: '{tags}', label: 'Tags', group: 'Tổng giá trị' },
  { key: '{total_discounts}', label: 'Chiết khấu đơn nhập', group: 'Tổng giá trị' },
  { key: '{total_discounts_rate}', label: 'Chiết khấu đơn nhập (%)', group: 'Tổng giá trị' },
  { key: '{total_discounts_value}', label: 'Chiết khấu đơn nhập (giá trị)', group: 'Tổng giá trị' },
  { key: '{total_tax_included_line}', label: 'Tổng thuế đã bao gồm trong sản phẩm', group: 'Tổng giá trị' },
  { key: '{total_amount_before_tax}', label: 'Tổng tiền trước thuế', group: 'Tổng giá trị' },
  { key: '{total_amount_after_tax}', label: 'Tổng tiền sau thuế', group: 'Tổng giá trị' },
  { key: '{total_amount_text}', label: 'Tổng tiền bằng chữ', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{account_name}', label: 'Người tạo', group: 'Thông tin khác' },
  { key: '{discount}', label: 'Chiết khấu', group: 'Tổng kết' },
  { key: '{line_ordered_quantity}', label: 'Số lượng đặt', group: 'Chi tiết sản phẩm' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Chi tiết sản phẩm' },
  { key: '{line_total}', label: 'Thành tiền', group: 'Chi tiết sản phẩm' },
  { key: '{line_variant}', label: 'Phiên bản sản phẩm', group: 'Chi tiết sản phẩm' },
  { key: '{supplier_phone_number}', label: 'SĐT nhà cung cấp', group: 'Thông tin nhà cung cấp' },
  { key: '{tax_vat}', label: 'Thuế VAT', group: 'Thông tin khác' },
  { key: '{total_order}', label: 'Tổng đơn hàng', group: 'Tổng kết' },
  { key: '{total}', label: 'Tổng cộng', group: 'Tổng kết' },
];

