import { TemplateVariable } from '../types';

export const DON_DOI_TRA_HANG_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_fax}', label: 'Số Fax', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  // Thông tin đơn hàng
  { key: '{order_code}', label: 'Mã đơn hàng', group: 'Thông tin đơn hàng' },
  { key: '{order_qr_code}', label: 'Mã đơn hàng dạng QR code', group: 'Thông tin đơn hàng' },
  { key: '{bar_code(code)}', label: 'Mã đơn hàng dạng mã vạch', group: 'Thông tin đơn hàng' },
  { key: '{order_return_code}', label: 'Mã đơn trả hàng', group: 'Thông tin đơn hàng' },
  { key: '{ship_on_min}', label: 'Ngày hẹn giao hàng từ', group: 'Thông tin đơn hàng' },
  { key: '{ship_on_max}', label: 'Thời gian hẹn giao hàng đến', group: 'Thông tin đơn hàng' },
  { key: '{assignee_name}', label: 'Người phụ trách', group: 'Thông tin đơn hàng' },
  { key: '{expected_delivery_type}', label: 'Vận chuyển dự kiến', group: 'Thông tin đơn hàng' },
  { key: '{shipping_address:full_name}', label: 'Người nhận', group: 'Thông tin đơn hàng' },
  { key: '{shipping_address:phone_number}', label: 'SĐT người nhận', group: 'Thông tin đơn hàng' },
  { key: '{shipping_address}', label: 'Địa chỉ nhận', group: 'Thông tin đơn hàng' },
  { key: '{customer_debt}', label: 'Nợ hiện tại', group: 'Thông tin đơn hàng' },
  { key: '{customer_debt_text}', label: 'Nợ KH bằng chữ', group: 'Thông tin đơn hàng' },
  { key: '{customer_debt_prev}', label: 'Nợ cũ', group: 'Thông tin đơn hàng' },
  { key: '{customer_debt_prev_text}', label: 'Nợ cũ KH bằng chữ', group: 'Thông tin đơn hàng' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin đơn hàng' },
  { key: '{created_on_time}', label: 'Thời gian tạo', group: 'Thông tin đơn hàng' },
  { key: '{modified_on}', label: 'Ngày cập nhật', group: 'Thông tin đơn hàng' },
  { key: '{modified_on_time}', label: 'Thời gian cập nhật', group: 'Thông tin đơn hàng' },
  { key: '{issued_on}', label: 'Ngày chứng từ', group: 'Thông tin đơn hàng' },
  { key: '{issued_on_time}', label: 'Thời gian chứng từ', group: 'Thông tin đơn hàng' },
  { key: '{source}', label: 'Nguồn', group: 'Thông tin đơn hàng' },
  { key: '{channel}', label: 'Kênh bán hàng', group: 'Thông tin đơn hàng' },
  { key: '{bar_code(reference_number)}', label: 'Tham chiếu dạng mã vạch', group: 'Thông tin đơn hàng' },
  { key: '{reference}', label: 'Tham chiếu', group: 'Thông tin đơn hàng' },
  { key: '{tag}', label: 'Thẻ Tag', group: 'Thông tin đơn hàng' },
  { key: '{order_status}', label: 'Trạng thái đơn hàng', group: 'Thông tin đơn hàng' },
  { key: '{fulfillment_status}', label: 'Trạng thái giao hàng', group: 'Thông tin đơn hàng' },
  { key: '{packed_status}', label: 'Trạng thái đóng gói', group: 'Thông tin đơn hàng' },
  { key: '{return_status}', label: 'Trạng thái trả hàng', group: 'Thông tin đơn hàng' },
  { key: '{payment_status}', label: 'Trạng thái thanh toán', group: 'Thông tin đơn hàng' },
  { key: '{expected_payment_method}', label: 'Thanh toán dự kiến', group: 'Thông tin đơn hàng' },
  { key: '{price_list_name}', label: 'Chính sách giá', group: 'Thông tin đơn hàng' },
  { key: '{currency_name}', label: 'Tiền tệ', group: 'Thông tin đơn hàng' },
  // Thông tin khách hàng
  { key: '{customer_code}', label: 'Mã khách hàng', group: 'Thông tin khách hàng' },
  { key: '{customer_name}', label: 'Tên khách hàng', group: 'Thông tin khách hàng' },
  { key: '{customer_contact}', label: 'Liên hệ khách hàng', group: 'Thông tin khách hàng' },
  { key: '{billing_address}', label: 'Địa chỉ gửi hóa đơn', group: 'Thông tin khách hàng' },
  { key: '{customer_phone_number}', label: 'SĐT khách hàng', group: 'Thông tin khách hàng' },
  { key: '{customer_email}', label: 'Email khách hàng', group: 'Thông tin khách hàng' },
  { key: '{customer_point}', label: 'Điểm của khách hàng', group: 'Thông tin khách hàng' },
  { key: '{customer_card}', label: 'Hạng thẻ', group: 'Thông tin khách hàng' },
  { key: '{customer_tax_number}', label: 'Mã số thuế của KH', group: 'Thông tin khách hàng' },
  // Thông tin giỏ hàng
  { key: '{line_stt}', label: 'STT', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_code}', label: 'Mã phiên bản sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_rate}', label: 'Thuế theo %', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_rate}', label: 'Chiết khấu sản phẩm %', group: 'Thông tin giỏ hàng' },
  { key: '{line_note}', label: 'Ghi chú sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_unit}', label: 'Đơn vị tính', group: 'Thông tin giỏ hàng' },
  { key: '{line_price_after_discount}', label: 'Giá sau chiết khấu trên 1 sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_promotion_or_loyalty}', label: 'Hàng tích điểm, KM', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_included}', label: 'Giá đã bao gồm thuế', group: 'Thông tin giỏ hàng' },
  { key: '{line_brand}', label: 'Thương hiệu sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{total_line_item_discount}', label: 'Tổng chiết khấu sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code2}', label: 'Mã lô - Số lượng bán sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code4}', label: 'Mã lô - NSX - NHH - Số lượng bán sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant}', label: 'Tên phiên bản sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_amount}', label: 'Thuế', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_amount}', label: 'Chiết khấu sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_price}', label: 'Giá bán', group: 'Thông tin giỏ hàng' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_barcode}', label: 'Mã Barcode', group: 'Thông tin giỏ hàng' },
  { key: '{line_amount_none_discount}', label: 'Tiền hàng (Giá * SL)', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_options}', label: 'Thuộc tính sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_category}', label: 'Loại sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{serials}', label: 'Serial', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code1}', label: 'Mã lô sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code3}', label: 'Mã lô - NSX - NHH sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_exclude}', label: 'Giá chưa bao gồm thuế', group: 'Thông tin giỏ hàng' },
  // Thông tin giỏ hàng trả
  { key: '{return_line_stt}', label: 'STT', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_line_unit}', label: 'Đơn vị tính', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_line_variant_code}', label: 'Mã phiên bản', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_line_price}', label: 'Giá bán', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_line_product_name}', label: 'Tên hàng', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_line_note}', label: 'Ghi chú sản phẩm', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_line_variant}', label: 'Tên phiên bản', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_line_amount}', label: 'Thành tiền', group: 'Thông tin giỏ hàng trả' },
  { key: '{return_serials}', label: 'Serial', group: 'Thông tin giỏ hàng trả' },
  // Tổng giá trị
  { key: '{return_total_quantity}', label: 'Tổng số lượng sản phẩm trả', group: 'Tổng giá trị' },
  { key: '{total_quantity}', label: 'Tổng số lượng hàng mua', group: 'Tổng giá trị' },
  { key: '{total_order_exchange_amount}', label: 'Tổng tiền cần thanh toán', group: 'Tổng giá trị' },
  { key: '{money_return}', label: 'Tổng tiền trả lại', group: 'Tổng giá trị' },
  { key: '{total_text}', label: 'Tổng tiền bằng chữ', group: 'Tổng giá trị' },
  { key: '{order_note}', label: 'Ghi chú', group: 'Tổng giá trị' },
  { key: '{total_remain}', label: 'Tiền còn lại khách phải trả', group: 'Tổng giá trị' },
  { key: '{payment_name}', label: 'Phương thức thanh toán', group: 'Tổng giá trị' },
  { key: '{promotion_name}', label: 'Tên khuyến mại', group: 'Tổng giá trị' },
  { key: '{promotion_code}', label: 'Mã chương trình khuyến mại', group: 'Tổng giá trị' },
  { key: '{order_discount}', label: 'Chiết khấu đơn hàng', group: 'Tổng giá trị' },
  { key: '{total_amount_before_tax}', label: 'Tổng tiền trước thuế', group: 'Tổng giá trị' },
  { key: '{total_amount_after_tax}', label: 'Tổng tiền sau thuế', group: 'Tổng giá trị' },
  { key: '{return_total_amount}', label: 'Tổng tiền hoàn trả', group: 'Tổng giá trị' },
  { key: '{total_amount}', label: 'Tổng tiền mua', group: 'Tổng giá trị' },
  { key: '{order_exchange_payment_note}', label: 'Nội dung thanh toán (Khách phải trả/Cần trả khách)', group: 'Tổng giá trị' },
  { key: '{payment_customer}', label: 'Tổng tiền khách đưa', group: 'Tổng giá trị' },
  { key: '{total}', label: 'Tổng tiền hàng', group: 'Tổng giá trị' },
  { key: '{total_none_discount}', label: 'Tổng tiền (Đơn giá * SL)', group: 'Tổng giá trị' },
  { key: '{total_discount}', label: 'Tổng chiết khấu của sản phẩm và đơn hàng', group: 'Tổng giá trị' },
  { key: '{product_discount}', label: 'Chiết khấu sản phẩm', group: 'Tổng giá trị' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng giá trị' },
  { key: '{delivery_fee}', label: 'Phí giao hàng', group: 'Tổng giá trị' },
  { key: '{order_discount_rate}', label: 'Chiết khấu đơn hàng theo %', group: 'Tổng giá trị' },
  { key: '{order_discount_value}', label: 'Chiết khấu đơn hàng theo giá trị', group: 'Tổng giá trị' },
  { key: '{total_extra_tax}', label: 'Tổng thuế phải trả thêm', group: 'Tổng giá trị' },
  { key: '{total_tax_included_line}', label: 'Tổng thuế đã bao gồm trong sản phẩm', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{account_name}', label: 'Người tạo', group: 'Thông tin khác' },
  { key: '{line_total}', label: 'Thành tiền', group: 'Chi tiết sản phẩm' },
  { key: '{note}', label: 'Ghi chú', group: 'Thông tin khác' },
  { key: '{reason_return}', label: 'Lý do trả hàng', group: 'Thông tin trả hàng' },
  { key: '{refund_status}', label: 'Trạng thái hoàn tiền', group: 'Thông tin hoàn tiền' },
];

