import { TemplateVariable } from '../types';

export const NHAN_GIAO_HANG_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  { key: '{location_phone_number}', label: 'Số điện thoại chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  // Thông tin đơn hàng
  { key: '{order_code}', label: 'Mã đơn hàng', group: 'Thông tin đơn hàng' },
  { key: '{order_qr_code}', label: 'Mã đơn hàng dạng QR code', group: 'Thông tin đơn hàng' },
  { key: '{order_bar_code}', label: 'Mã đơn hàng dạng mã vạch', group: 'Thông tin đơn hàng' },
  { key: '{modified_on}', label: 'Ngày cập nhật', group: 'Thông tin đơn hàng' },
  { key: '{received_on}', label: 'Ngày nhận', group: 'Thông tin đơn hàng' },
  { key: '{modified_on_time}', label: 'Thời gian cập nhật', group: 'Thông tin đơn hàng' },
  { key: '{received_on_time}', label: 'Thời gian nhận', group: 'Thông tin đơn hàng' },
  { key: '{customer_name}', label: 'Tên khách hàng', group: 'Thông tin đơn hàng' },
  { key: '{shipping_address}', label: 'Giao hàng đến', group: 'Thông tin đơn hàng' },
  { key: '{customer_phone_number}', label: 'SĐT khách hàng', group: 'Thông tin đơn hàng' },
  { key: '{delivery_type}', label: 'Phương thức vận chuyển', group: 'Thông tin đơn hàng' },
  { key: '{tracking_number}', label: 'Mã vận đơn', group: 'Thông tin đơn hàng' },
  { key: '{tracking_number_qr_code}', label: 'Mã vận đơn dạng QR code', group: 'Thông tin đơn hàng' },
  { key: '{tracking_number_bar_code}', label: 'Mã vận đơn dạng mã vạch', group: 'Thông tin đơn hàng' },
  { key: '{ship_on_min}', label: 'Ngày hẹn giao từ', group: 'Thông tin đơn hàng' },
  { key: '{status}', label: 'Trạng thái', group: 'Thông tin đơn hàng' },
  { key: '{city}', label: 'Tỉnh thành giao hàng', group: 'Thông tin đơn hàng' },
  { key: '{partner_type}', label: 'Loại đối tác', group: 'Thông tin đơn hàng' },
  { key: '{shipper_deposits}', label: 'Số tiền cọc trước', group: 'Thông tin đơn hàng' },
  { key: '{reason_cancel}', label: 'Lý do hủy đơn', group: 'Thông tin đơn hàng' },
  { key: '{account_name}', label: 'Nhân viên tạo đơn', group: 'Thông tin đơn hàng' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin đơn hàng' },
  { key: '{vnpost_crm_code}', label: 'Mã CRM VNPost', group: 'Thông tin đơn hàng' },
  { key: '{vnpost_crm_bar_code}', label: 'Mã CRM VNPost dạng mã vạch', group: 'Thông tin đơn hàng' },
  { key: '{packed_on}', label: 'Ngày đóng gói', group: 'Thông tin đơn hàng' },
  { key: '{packed_on_time}', label: 'Thời gian đóng gói', group: 'Thông tin đơn hàng' },
  { key: '{shipped_on_time}', label: 'Thời gian chuyển hàng', group: 'Thông tin đơn hàng' },
  { key: '{service_name}', label: 'Dịch vụ', group: 'Thông tin đơn hàng' },
  { key: '{billing_address}', label: 'Nơi giao hàng', group: 'Thông tin đơn hàng' },
  { key: '{customer_email}', label: 'Email khách hàng', group: 'Thông tin đơn hàng' },
  { key: '{delivery_service_provider}', label: 'Đối tác vận chuyển', group: 'Thông tin đơn hàng' },
  { key: '{receiver_name}', label: 'Người nhận', group: 'Thông tin đơn hàng' },
  { key: '{packing_weight}', label: 'Khối lượng đóng gói', group: 'Thông tin đơn hàng' },
  { key: '{creator_name}', label: 'Nhân viên tạo phiếu giao hàng', group: 'Thông tin đơn hàng' },
  { key: '{created_on_time}', label: 'Thời gian tạo', group: 'Thông tin đơn hàng' },
  { key: '{ship_on_max}', label: 'Ngày hẹn giao đến', group: 'Thông tin đơn hàng' },
  { key: '{district}', label: 'Quận huyện giao hàng', group: 'Thông tin đơn hàng' },
  { key: '{partner_phone_number}', label: 'Số ĐT đối tác', group: 'Thông tin đơn hàng' },
  { key: '{customer_phone_number_hide}', label: 'SĐT khách hàng - ẩn 4 số giữa', group: 'Thông tin đơn hàng' },
  { key: '{receiver_phone}', label: 'Số điện thoại người nhận', group: 'Thông tin đơn hàng' },
  { key: '{receiver_phone_hide}', label: 'Số điện thoại người nhận - ẩn 4 số giữa', group: 'Thông tin đơn hàng' },
  { key: '{pushing_status}', label: 'Trạng thái đẩy đơn', group: 'Thông tin đơn hàng' },
  { key: '{route_code_se}', label: 'Mã phân tuyến Sapo Express', group: 'Thông tin đơn hàng' },
  { key: '{sorting_code}', label: 'Mã định danh bưu cục', group: 'Thông tin đơn hàng' },
  { key: '{sorting_code_bar_code}', label: 'Mã định danh dạng mã vạch', group: 'Thông tin đơn hàng' },
  // Tổng giá trị
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total}', label: 'Tổng tiền hàng', group: 'Tổng giá trị' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng giá trị' },
  { key: '{delivery_fee}', label: 'Phí giao hàng', group: 'Tổng giá trị' },
  { key: '{shipment_note}', label: 'Ghi chú', group: 'Tổng giá trị' },
  { key: '{cod_amount}', label: 'Tiền thu hộ', group: 'Tổng giá trị' },
  { key: '{total_amount}', label: 'Khách phải trả', group: 'Tổng giá trị' },
  { key: '{fulfillment_discount}', label: 'Chiết khấu', group: 'Tổng giá trị' },
  { key: '{freight_amount}', label: 'Phí trả shipper', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{cod}', label: 'Tiền thu hộ (COD)', group: 'Thông tin khác' },
  { key: '{note}', label: 'Ghi chú', group: 'Thông tin khác' },
  { key: '{shipment_barcode}', label: 'Mã vạch vận đơn', group: 'Thông tin vận chuyển' },
  { key: '{shipment_code}', label: 'Mã vận đơn', group: 'Thông tin vận chuyển' },
  { key: '{shipment_qrcode}', label: 'QR code vận đơn', group: 'Thông tin vận chuyển' },
  { key: '{total_weight_g}', label: 'Tổng khối lượng (g)', group: 'Tổng kết' },
  { key: '{total_weight_kg}', label: 'Tổng khối lượng (kg)', group: 'Tổng kết' },
];

