import { TemplateVariable } from '../types';

export const PHIEU_NHAP_KHO_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_fax}', label: 'Số Fax', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{account_name}', label: 'Tên người tạo', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  // Thông tin đơn hàng
  { key: '{purchase_order_code}', label: 'Mã đơn nhập hàng', group: 'Thông tin đơn hàng' },
  { key: '{modified_on}', label: 'Ngày cập nhật', group: 'Thông tin đơn hàng' },
  { key: '{received_on_time}', label: 'Thời gian nhập kho', group: 'Thông tin đơn hàng' },
  { key: '{supplier_name}', label: 'Tên NCC', group: 'Thông tin đơn hàng' },
  { key: '{supplier_code}', label: 'Mã NCC', group: 'Thông tin đơn hàng' },
  { key: '{supplier_debt_text}', label: 'Nợ NCC bằng chữ', group: 'Thông tin đơn hàng' },
  { key: '{supplier_debt_prev_text}', label: 'Nợ cũ NCC bằng chữ', group: 'Thông tin đơn hàng' },
  { key: '{supplier_phone}', label: 'SĐT NCC', group: 'Thông tin đơn hàng' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin đơn hàng' },
  { key: '{received_on}', label: 'Ngày nhập kho', group: 'Thông tin đơn hàng' },
  { key: '{receipt_code}', label: 'Mã phiếu nhập kho', group: 'Thông tin đơn hàng' },
  { key: '{note}', label: 'Ghi chú', group: 'Thông tin đơn hàng' },
  { key: '{supplier_debt}', label: 'Nợ NCC', group: 'Thông tin đơn hàng' },
  { key: '{supplier_debt_prev}', label: 'Nợ cũ NCC', group: 'Thông tin đơn hàng' },
  { key: '{supplier_email}', label: 'Email NCC', group: 'Thông tin đơn hàng' },
  { key: '{reference}', label: 'Tham chiếu', group: 'Thông tin đơn hàng' },
  // Thông tin giỏ hàng
  { key: '{line_stt}', label: 'STT', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_code}', label: 'Mã phiên bản sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_unit}', label: 'Đơn vị tính', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_rate}', label: 'Chiết khấu sản phẩm %', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_barcode}', label: 'Mã Barcode', group: 'Thông tin giỏ hàng' },
  { key: '{bin_location}', label: 'Điểm lưu kho', group: 'Thông tin giỏ hàng' },
  { key: '{line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_options}', label: 'Thuộc tính sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_brand}', label: 'Thương hiệu sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_rate}', label: 'Thuế (%)', group: 'Thông tin giỏ hàng' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_name}', label: 'Tên phiên bản sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax}', label: 'Loại thuế theo từng mặt hàng', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_amount}', label: 'Chiết khấu sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_price}', label: 'Giá bán', group: 'Thông tin giỏ hàng' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Thông tin giỏ hàng' },
  { key: '{line_category}', label: 'Loại sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{serials}', label: 'Serial', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_amount}', label: 'Thuế (giá trị)', group: 'Thông tin giỏ hàng' },
  // Tổng giá trị
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng giá trị' },
  { key: '{total_discounts}', label: 'Tổng chiết khấu', group: 'Tổng giá trị' },
  { key: '{total_amount_text}', label: 'Tổng tiền bằng chữ', group: 'Tổng giá trị' },
  { key: '{total_price}', label: 'Tổng tiền', group: 'Tổng giá trị' },
  { key: '{total}', label: 'Tổng tiền hàng', group: 'Tổng giá trị' },
  { key: '{total_landed_costs}', label: 'Tổng chi phí', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{discount}', label: 'Chiết khấu', group: 'Tổng kết' },
  { key: '{line_ordered_quantity}', label: 'Số lượng đặt', group: 'Chi tiết sản phẩm' },
  { key: '{line_received_quantity}', label: 'Số lượng nhận', group: 'Chi tiết sản phẩm' },
  { key: '{line_total}', label: 'Thành tiền', group: 'Chi tiết sản phẩm' },
  { key: '{line_variant}', label: 'Phiên bản sản phẩm', group: 'Chi tiết sản phẩm' },
  { key: '{order_supplier_code}', label: 'Mã đơn nhà cung cấp', group: 'Thông tin nhà cung cấp' },
  { key: '{paid}', label: 'Đã thanh toán', group: 'Thông tin khác' },
  { key: '{remaining}', label: 'Còn lại', group: 'Thông tin khác' },
  { key: '{stock_in_code}', label: 'Mã phiếu nhập kho', group: 'Thông tin kho' },
  { key: '{stock_in_status}', label: 'Trạng thái nhập kho', group: 'Thông tin kho' },
  { key: '{tax_vat}', label: 'Thuế VAT', group: 'Thông tin khác' },
  { key: '{total_order}', label: 'Tổng đơn hàng', group: 'Tổng kết' },
];

