import { TemplateVariable } from '../types';

export const PHIEU_YEU_CAU_DONG_GOI_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_fax}', label: 'Số Fax', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  // Thông tin đóng gói
  { key: '{code}', label: 'Mã đóng gói', group: 'Thông tin đóng gói' },
  { key: '{account_name}', label: 'Nhân viên yêu đóng gói', group: 'Thông tin đóng gói' },
  { key: '{packed_processing_account_name}', label: 'Nhân viên xác nhận đóng gói', group: 'Thông tin đóng gói' },
  { key: '{cancel_account_name}', label: 'Nhân viên hủy đóng gói', group: 'Thông tin đóng gói' },
  { key: '{assignee_name}', label: 'Nhân viên được gán cho đóng gói', group: 'Thông tin đóng gói' },
  { key: '{shipping_address}', label: 'Địa chỉ giao hàng', group: 'Thông tin đóng gói' },
  { key: '{customer_name}', label: 'Tên khách hàng', group: 'Thông tin đóng gói' },
  { key: '{customer_phone_number}', label: 'SĐT khách hàng', group: 'Thông tin đóng gói' },
  { key: '{customer_phone_number_hide}', label: 'SĐT khách hàng - ẩn 4 số giữa', group: 'Thông tin đóng gói' },
  { key: '{customer_email}', label: 'Email khách hàng', group: 'Thông tin đóng gói' },
  { key: '{status}', label: 'Trạng thái đóng gói', group: 'Thông tin đóng gói' },
  { key: '{bar_code(code)}', label: 'Mã đóng gói dạng mã vạch', group: 'Thông tin đóng gói' },
  { key: '{created_on}', label: 'Ngày tạo đóng gói', group: 'Thông tin đóng gói' },
  { key: '{created_on_time}', label: 'Thời gian tạo đóng gói', group: 'Thông tin đóng gói' },
  { key: '{packed_on}', label: 'Ngày xác nhận đóng gói', group: 'Thông tin đóng gói' },
  { key: '{packed_on_time}', label: 'Thời gian xác nhận đóng gói', group: 'Thông tin đóng gói' },
  { key: '{cancel_date}', label: 'Ngày hủy đóng gói', group: 'Thông tin đóng gói' },
  { key: '{ship_on_min}', label: 'Ngày hẹn giao hàng từ', group: 'Thông tin đóng gói' },
  { key: '{ship_on_max}', label: 'Ngày hẹn giao hàng đến', group: 'Thông tin đóng gói' },
  { key: '{order_code}', label: 'Mã đơn hàng', group: 'Thông tin đóng gói' },
  { key: '{bar_code(order_code)}', label: 'Mã đơn hàng dạng mã vạch', group: 'Thông tin đóng gói' },
  { key: '{order_note}', label: 'Ghi chú đơn hàng', group: 'Thông tin đóng gói' },
  // Thông tin giỏ hàng
  { key: '{line_stt}', label: 'STT', group: 'Thông tin giỏ hàng' },
  { key: '{line_unit}', label: 'Đơn vị tính', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_rate}', label: 'Chiết khấu sản phẩm %', group: 'Thông tin giỏ hàng' },
  { key: '{line_note}', label: 'Ghi chú sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_rate}', label: '% Thuế', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant}', label: 'Tên phiên bản sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code2}', label: 'Mã lô - Số lượng bán sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code4}', label: 'Mã lô - NSX -NHH - Số lượng bán sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax}', label: 'Loại thuế theo từng mặt hàng', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_amount}', label: 'Chiết khấu sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_price}', label: 'Giá bán', group: 'Thông tin giỏ hàng' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_code}', label: 'Mã sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code1}', label: 'Mã lô sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code3}', label: 'Mã lô - NSX - NHH sản phẩm', group: 'Thông tin giỏ hàng' },
  // Tổng giá trị
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng giá trị' },
  { key: '{fulfillment_discount}', label: 'Chiết khấu', group: 'Tổng giá trị' },
  { key: '{total}', label: 'Tổng tiền hàng', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{assigned_employee}', label: 'Nhân viên được gán', group: 'Thông tin khác' },
  { key: '{bin_location}', label: 'Vị trí kho', group: 'Thông tin khác' },
  { key: '{carrier_name}', label: 'Tên đơn vị vận chuyển', group: 'Thông tin khác' },
  { key: '{cod}', label: 'Tiền thu hộ (COD)', group: 'Thông tin khác' },
  { key: '{deadline}', label: 'Hạn hoàn thành', group: 'Thông tin khác' },
  { key: '{packing_note}', label: 'Ghi chú đóng gói', group: 'Thông tin đóng gói' },
  { key: '{packing_request_code}', label: 'Mã yêu cầu đóng gói', group: 'Thông tin đóng gói' },
  { key: '{priority}', label: 'Độ ưu tiên', group: 'Thông tin khác' },
  { key: '{service_name}', label: 'Tên dịch vụ', group: 'Thông tin khác' },
  { key: '{special_request}', label: 'Yêu cầu đặc biệt', group: 'Thông tin khác' },
  { key: '{total_weight}', label: 'Tổng khối lượng', group: 'Tổng kết' },
];

