import { TemplateVariable } from '../types';

export const PHIEU_TONG_KET_BAN_HANG_VARIABLES: TemplateVariable[] = [
  // Thông tin
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin' },
  { key: '{account_name}', label: 'Tên nhân viên', group: 'Thông tin' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin' },
  { key: '{store_phone_number}', label: 'Số ĐT cửa hàng', group: 'Thông tin' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin' },
  { key: '{date_print}', label: 'Ngày in', group: 'Thông tin' },
  { key: '{time_print}', label: 'Thời gian in', group: 'Thông tin' },
  { key: '{print_date}', label: 'Ngày in (chuẩn)', group: 'Thông tin' },
  { key: '{print_time}', label: 'Giờ in (chuẩn)', group: 'Thông tin' },
  { key: '{time_filter}', label: 'Ngày lọc', group: 'Thông tin' },
  { key: '{source_name}', label: 'Nguồn bán hàng', group: 'Thông tin' },
  { key: '{total_quantity_order_finished}', label: 'Số đơn hàng bán ra', group: 'Thông tin' },
  { key: '{total_quantity_line_item_fulfillment}', label: 'Số lượng hàng bán ra', group: 'Thông tin' },
  { key: '{total_quantity_line_item_return}', label: 'Số lượng hàng trả lại', group: 'Thông tin' },
  { key: '{total_line_amount}', label: 'Doanh thu', group: 'Thông tin' },
  { key: '{total_order_payment}', label: 'Khách thanh toán', group: 'Thông tin' },
  { key: '{total_order_return_payment}', label: 'Hoàn lại khách', group: 'Thông tin' },
  { key: '{total_real_receipt}', label: 'Thực thu', group: 'Thông tin' },
  { key: '{real_receipt_cash}', label: 'Thực thu tiền mặt', group: 'Thông tin' },
  { key: '{real_receipt_transfer}', label: 'Thực thu chuyển khoản', group: 'Thông tin' },
  { key: '{real_receipt_mpos}', label: 'Thực thu quẹt thẻ', group: 'Thông tin' },
  { key: '{real_receipt_cod}', label: 'Thực thu COD', group: 'Thông tin' },
  { key: '{real_receipt_online}', label: 'Thực thu online', group: 'Thông tin' },
  { key: '{debt}', label: 'Nợ còn lại phải thu', group: 'Thông tin' },
  { key: '{receipt_in_day}', label: 'Tổng thu', group: 'Thông tin' },
  { key: '{receipt_cash}', label: 'Tổng thu tiền mặt', group: 'Thông tin' },
  { key: '{receipt_transfer}', label: 'Tổng thu chuyển khoản', group: 'Thông tin' },
  { key: '{receipt_mpos}', label: 'Tổng thu quẹt thẻ', group: 'Thông tin' },
  { key: '{receipt_cod}', label: 'Tổng thu COD', group: 'Thông tin' },
  { key: '{receipt_online}', label: 'Tổng thu online', group: 'Thông tin' },
  { key: '{payment_in_day}', label: 'Tổng chi', group: 'Thông tin' },
  { key: '{payment_cash}', label: 'Tổng chi tiền mặt', group: 'Thông tin' },
  { key: '{payment_transfer}', label: 'Tổng chi chuyển khoản', group: 'Thông tin' },
  { key: '{payment_mpos}', label: 'Tổng chi quẹt thẻ', group: 'Thông tin' },
  { key: '{stt_order_finish}', label: 'STT đơn hàng bán', group: 'Thông tin' },
  { key: '{order_code}', label: 'Mã đơn', group: 'Thông tin' },
  { key: '{amount_order_finished}', label: 'Tiền hàng', group: 'Thông tin' },
  { key: '{discount_order_finished}', label: 'Chiết khấu', group: 'Thông tin' },
  { key: '{tax_order_finished}', label: 'Thuế', group: 'Thông tin' },
  { key: '{total_order_finished}', label: 'Doanh thu', group: 'Thông tin' },
  { key: '{stt_item_fulfillment}', label: 'STT đơn hàng bán', group: 'Thông tin' },
  { key: '{sku_fulfillment}', label: 'Mã SKU hàng bán', group: 'Thông tin' },
  { key: '{variant_name_fulfillment}', label: 'Tên hàng bán', group: 'Thông tin' },
  { key: '{quantity_item_fulfilment}', label: 'SL hàng bán', group: 'Thông tin' },
  { key: '{amount_item_fulfilment}', label: 'Giá trị hàng bán', group: 'Thông tin' },
  { key: '{stt_item_return}', label: 'STT hàng trả lại', group: 'Thông tin' },
  { key: '{sku_return}', label: 'Mã SKU hàng trả', group: 'Thông tin' },
  { key: '{variant_name_return}', label: 'Tên hàng trả', group: 'Thông tin' },
  { key: '{quantity_item_return}', label: 'SL hàng trả', group: 'Thông tin' },
  { key: '{amount_item_return}', label: 'Giá trị hàng trả', group: 'Thông tin' },
  { key: '{payment_method_name}', label: 'Tên hình thức thanh toán', group: 'Thông tin' },
  { key: '{payment_method_amount}', label: 'Giá trị thanh toán theo hình thức', group: 'Thông tin' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{bank_transfer_amount}', label: 'Tiền chuyển khoản', group: 'Tổng kết' },
  { key: '{card_amount}', label: 'Tiền thẻ', group: 'Tổng kết' },
  { key: '{cash_amount}', label: 'Tiền mặt', group: 'Tổng kết' },
  { key: '{cod_amount}', label: 'Tiền COD', group: 'Tổng kết' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin khác' },
  { key: '{delivery_revenue}', label: 'Doanh thu giao hàng', group: 'Thông tin khác' },
  { key: '{ewallet_amount}', label: 'Tiền ví điện tử', group: 'Tổng kết' },
  { key: '{from_date}', label: 'Từ ngày', group: 'Thông tin khác' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Chi tiết sản phẩm' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Chi tiết sản phẩm' },
  { key: '{line_quantity}', label: 'Số lượng', group: 'Chi tiết sản phẩm' },
  { key: '{line_stt}', label: 'STT', group: 'Chi tiết sản phẩm' },
  { key: '{note}', label: 'Ghi chú', group: 'Thông tin khác' },
  { key: '{period}', label: 'Kỳ báo cáo', group: 'Thông tin khác' },
  { key: '{sales_revenue}', label: 'Doanh thu bán hàng', group: 'Thông tin khác' },
  { key: '{to_date}', label: 'Đến ngày', group: 'Thông tin khác' },
  { key: '{total_collected}', label: 'Tổng thu', group: 'Tổng kết' },
  { key: '{total_discount}', label: 'Tổng chiết khấu', group: 'Tổng kết' },
  { key: '{total_orders}', label: 'Tổng số đơn', group: 'Tổng kết' },
  { key: '{total_returns}', label: 'Tổng trả hàng', group: 'Tổng kết' },
  { key: '{total_revenue}', label: 'Tổng doanh thu', group: 'Tổng kết' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng kết' },
];

