import { TemplateVariable } from '../types';

export const PHIEU_YEU_CAU_BAO_HANH_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  // Thông tin phiếu yêu cầu
  { key: '{account_name}', label: 'Tên nhân viên tạo', group: 'Thông tin phiếu yêu cầu' },
  { key: '{warranty_claim_card_code}', label: 'Mã phiếu yêu cầu bảo hành', group: 'Thông tin phiếu yêu cầu' },
  { key: '{modified_on}', label: 'Ngày cập nhật', group: 'Thông tin phiếu yêu cầu' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin phiếu yêu cầu' },
  { key: '{reference}', label: 'Ghi chú', group: 'Thông tin phiếu yêu cầu' },
  { key: '{customer_name}', label: 'Tên khách hàng', group: 'Thông tin phiếu yêu cầu' },
  { key: '{customer_phone_number}', label: 'SĐT khách hàng', group: 'Thông tin phiếu yêu cầu' },
  { key: '{customer_address1}', label: 'Địa chỉ khách hàng', group: 'Thông tin phiếu yêu cầu' },
  { key: '{customer_group}', label: 'Nhóm khách hàng', group: 'Thông tin phiếu yêu cầu' },
  { key: '{tag}', label: 'Thẻ tag', group: 'Thông tin phiếu yêu cầu' },
  // Thông tin sản phẩm
  { key: '{line_stt}', label: 'STT', group: 'Thông tin sản phẩm' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_name}', label: 'Tên phiên bản sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_sku}', label: 'Mã SKU', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_barcode}', label: 'Mã Barcode', group: 'Thông tin sản phẩm' },
  { key: '{serials}', label: 'Mã serial', group: 'Thông tin sản phẩm' },
  { key: '{warranty_card_code}', label: 'Mã phiếu bảo hành', group: 'Thông tin sản phẩm' },
  { key: '{line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_type}', label: 'Loại yêu cầu', group: 'Thông tin sản phẩm' },
  { key: '{line_received_on}', label: 'Ngày hẹn trả', group: 'Thông tin sản phẩm' },
  { key: '{line_status}', label: 'Trạng thái', group: 'Thông tin sản phẩm' },
  { key: '{line_expense_title}', label: 'Tên chi phí/ dịch vụ', group: 'Thông tin sản phẩm' },
  { key: '{line_expense_amount}', label: 'Giá trị chi phí/ dịch vụ', group: 'Thông tin sản phẩm' },
  { key: '{line_expense_total_amount}', label: 'Tổng chi phí trên sản phẩm', group: 'Thông tin sản phẩm' },
  // Tổng giá trị
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total_amount}', label: 'Tổng tiền khách trả', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{accessories}', label: 'Phụ kiện kèm theo', group: 'Thông tin khác' },
  { key: '{created_on_time}', label: 'Giờ tạo', group: 'Thông tin khác' },
  { key: '{customer_address}', label: 'Địa chỉ khách hàng', group: 'Thông tin khách hàng' },
  { key: '{customer_code}', label: 'Mã khách hàng', group: 'Thông tin khách hàng' },
  { key: '{customer_email}', label: 'Email khách hàng', group: 'Thông tin khách hàng' },
  { key: '{device_condition}', label: 'Tình trạng thiết bị', group: 'Thông tin khác' },
  { key: '{expected_completion_date}', label: 'Ngày dự kiến hoàn thành', group: 'Thông tin khác' },
  { key: '{issue_description}', label: 'Mô tả sự cố', group: 'Thông tin khác' },
  { key: '{issue_type}', label: 'Loại sự cố', group: 'Thông tin khác' },
  { key: '{note}', label: 'Ghi chú', group: 'Thông tin khác' },
  { key: '{order_code}', label: 'Mã đơn hàng', group: 'Thông tin đơn hàng' },
  { key: '{priority}', label: 'Độ ưu tiên', group: 'Thông tin khác' },
  { key: '{product_code}', label: 'Mã sản phẩm', group: 'Thông tin khác' },
  { key: '{product_name}', label: 'Tên sản phẩm', group: 'Thông tin khác' },
  { key: '{purchase_date}', label: 'Ngày mua', group: 'Thông tin khác' },
  { key: '{received_by}', label: 'Người tiếp nhận', group: 'Thông tin khác' },
  { key: '{serial_number}', label: 'Số serial', group: 'Thông tin khác' },
  { key: '{status}', label: 'Trạng thái', group: 'Thông tin khác' },
  { key: '{technician_name}', label: 'Kỹ thuật viên', group: 'Thông tin khác' },
  { key: '{warranty_duration}', label: 'Thời hạn bảo hành', group: 'Thông tin bảo hành' },
  { key: '{warranty_expired_on}', label: 'Ngày hết bảo hành', group: 'Thông tin bảo hành' },
  { key: '{warranty_request_code}', label: 'Mã yêu cầu bảo hành', group: 'Thông tin bảo hành' },
];

