import { TemplateVariable } from '../types';

export const PHIEU_CHI_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  // Thông tin
  { key: '{payment_voucher_code}', label: 'Mã', group: 'Thông tin' },
  { key: '{object_name}', label: 'Tên người nhận', group: 'Thông tin' },
  { key: '{object_phone_number}', label: 'SĐT người nhận', group: 'Thông tin' },
  { key: '{total_text}', label: 'Số tiền bằng chữ', group: 'Thông tin' },
  { key: '{note}', label: 'Ghi chú', group: 'Thông tin' },
  { key: '{account_name}', label: 'Người tạo phiếu', group: 'Thông tin' },
  { key: '{group_name}', label: 'Loại phiếu chi', group: 'Thông tin' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin' },
  { key: '{counted}', label: 'Hạch toán KQKD', group: 'Thông tin' },
  { key: '{customer_debt_before_create_payment}', label: 'Nợ KH trước khi tạo phiếu', group: 'Thông tin' },
  { key: '{customer_debt_before_create_payment_text}', label: 'Nợ KH trước khi tạo phiếu bằng chữ', group: 'Thông tin' },
  { key: '{customer_debt_after_create_payment}', label: 'Nợ KH sau khi tạo phiếu', group: 'Thông tin' },
  { key: '{customer_debt_after_create_payment_text}', label: 'Nợ KH sau khi tạo phiếu bằng chữ', group: 'Thông tin' },
  { key: '{supplier_debt_before_create_payment}', label: 'Nợ NCC trước khi tạo phiếu', group: 'Thông tin' },
  { key: '{supplier_debt_before_create_payment_text}', label: 'Nợ NCC trước khi tạo phiếu bằng chữ', group: 'Thông tin' },
  { key: '{supplier_debt_after_create_payment}', label: 'Nợ NCC sau khi tạo phiếu', group: 'Thông tin' },
  { key: '{supplier_debt_after_create_payment_text}', label: 'Nợ NCC sau khi tạo phiếu bằng chữ', group: 'Thông tin' },
  { key: '{issued_on}', label: 'Ngày ghi nhận', group: 'Thông tin' },
  { key: '{object_address}', label: 'Địa chỉ người nhận', group: 'Thông tin' },
  { key: '{amount}', label: 'Số tiền', group: 'Thông tin' },
  { key: '{reference}', label: 'Tham chiếu', group: 'Thông tin' },
  { key: '{issued_on_time}', label: 'Thời gian ghi nhận', group: 'Thông tin' },
  { key: '{payment_method_name}', label: 'Phương thức thanh toán', group: 'Thông tin' },
  { key: '{object_type}', label: 'Loại người nhận', group: 'Thông tin' },
  { key: '{document_root_code}', label: 'Chứng từ gốc', group: 'Thông tin' },
  { key: '{supplier_debt}', label: 'Nợ nhà cung cấp hiện tại', group: 'Thông tin' },
  { key: '{supplier_debt_text}', label: 'Nợ nhà cung cấp hiện tại bằng chữ', group: 'Thông tin' },
  { key: '{supplier_debt_prev}', label: 'Nợ cũ nhà cung cấp', group: 'Thông tin' },
  { key: '{supplier_debt_prev_text}', label: 'Nợ cũ nhà cung cấp bằng chữ', group: 'Thông tin' },
  { key: '{customer_debt}', label: 'Nợ khách hàng hiện tại', group: 'Thông tin' },
  { key: '{customer_debt_text}', label: 'Nợ khách hàng hiện tại bằng chữ', group: 'Thông tin' },
  { key: '{customer_debt_prev}', label: 'Nợ cũ khách hàng', group: 'Thông tin' },
  { key: '{customer_debt_prev_text}', label: 'Nợ cũ khách hàng bằng chữ', group: 'Thông tin' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{amount_text}', label: 'Số tiền bằng chữ', group: 'Tổng kết' },
  { key: '{description}', label: 'Diễn giải', group: 'Thông tin khác' },
  { key: '{payment_barcode}', label: 'Mã vạch phiếu chi', group: 'Thông tin thanh toán' },
  { key: '{payment_method}', label: 'Phương thức thanh toán', group: 'Thông tin thanh toán' },
];

