import { TemplateVariable } from '../types';

export const PHIEU_DONG_GOI_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_fax}', label: 'Số Fax', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  { key: '{location_country}', label: 'Quốc gia (chi nhánh)', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  // Thông tin gói hàng
  { key: '{order_code}', label: 'Mã đơn hàng', group: 'Thông tin gói hàng' },
  { key: '{modified_on}', label: 'Ngày cập nhật', group: 'Thông tin gói hàng' },
  { key: '{shipped_on}', label: 'Ngày chuyển hàng', group: 'Thông tin gói hàng' },
  { key: '{shipped_on_time}', label: 'Thời gian chuyển hàng', group: 'Thông tin gói hàng' },
  { key: '{billing_address}', label: 'Địa chỉ gửi hóa đơn', group: 'Thông tin gói hàng' },
  { key: '{shipping_address}', label: 'Giao hàng đến', group: 'Thông tin gói hàng' },
  { key: '{customer_email}', label: 'Email khách hàng', group: 'Thông tin gói hàng' },
  { key: '{package_note}', label: 'Ghi chú', group: 'Thông tin gói hàng' },
  { key: '{created_on_time}', label: 'Thời gian tạo', group: 'Thông tin gói hàng' },
  { key: '{customer_name}', label: 'Tên khách hàng', group: 'Thông tin gói hàng' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin gói hàng' },
  { key: '{modified_on_time}', label: 'Thời gian cập nhật', group: 'Thông tin gói hàng' },
  { key: '{packed_on}', label: 'Ngày đóng gói', group: 'Thông tin gói hàng' },
  { key: '{packed_on_time}', label: 'Thời gian đóng gói', group: 'Thông tin gói hàng' },
  { key: '{order_note}', label: 'Ghi chú đơn hàng', group: 'Thông tin gói hàng' },
  { key: '{fulfillment_status}', label: 'Trạng thái', group: 'Thông tin gói hàng' },
  { key: '{customer_phone_number}', label: 'SĐT khách hàng', group: 'Thông tin gói hàng' },
  { key: '{customer_phone_number_hide}', label: 'SĐT khách hàng - ẩn 4 số giữa', group: 'Thông tin gói hàng' },
  // Thông tin giỏ hàng
  { key: '{line_stt}', label: 'STT', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_code}', label: 'Mã phiên bản sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_unit}', label: 'Đơn vị tính', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_rate}', label: 'Chiết khấu sản phẩm %', group: 'Thông tin giỏ hàng' },
  { key: '{line_note}', label: 'Ghi chú sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_product_category}', label: 'Loại sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_rate}', label: '% Thuế', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_barcode}', label: 'Mã vạch phiên bản sp', group: 'Thông tin giỏ hàng' },
  { key: '{line_price_after_discount}', label: 'Giá sau chiết khấu/sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code1}', label: 'Mã lô sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code3}', label: 'Mã lô - NSX - NHH sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_composite_variant_code}', label: 'Mã thành phần combo', group: 'Thông tin giỏ hàng' },
  { key: '{line_composite_variant_name}', label: 'Tên thành phần combo', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_exclude}', label: 'Giá chưa bao gồm thuế', group: 'Thông tin giỏ hàng' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant}', label: 'Tên phiên bản sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax}', label: 'Loại thuế theo từng mặt hàng', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_amount}', label: 'Chiết khấu sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_price}', label: 'Giá bán', group: 'Thông tin giỏ hàng' },
  { key: '{line_product_brand}', label: 'Nhãn hiệu', group: 'Thông tin giỏ hàng' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_options}', label: 'Thuộc tính sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_amount}', label: 'Thuế (giá trị)', group: 'Thông tin giỏ hàng' },
  { key: '{serials}', label: 'Serial', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code2}', label: 'Mã lô - Số lượng bán sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code4}', label: 'Mã lô - NSX - NHH - Số lượng bán sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_composite_unit}', label: 'ĐV thành phần combo', group: 'Thông tin giỏ hàng' },
  { key: '{line_composite_quantity}', label: 'SL thành phần combo', group: 'Thông tin giỏ hàng' },
  { key: '{line_tax_included}', label: 'Giá đã bao gồm thuế', group: 'Thông tin giỏ hàng' },
  // Tổng giá trị
  { key: '{total}', label: 'Tổng tiền hàng', group: 'Tổng giá trị' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng giá trị' },
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total_amount_before_tax}', label: 'Tổng tiền trước thuế', group: 'Tổng giá trị' },
  { key: '{total_amount_after_tax}', label: 'Tổng tiền sau thuế', group: 'Tổng giá trị' },
  { key: '{total_amount}', label: 'Khách phải trả', group: 'Tổng giá trị' },
  { key: '{fulfillment_discount}', label: 'Chiết khấu', group: 'Tổng giá trị' },
  { key: '{total_amount_text}', label: 'Tổng tiền bằng chữ', group: 'Tổng giá trị' },
  { key: '{total_extra_tax}', label: 'Tổng thuế phải trả thêm', group: 'Tổng giá trị' },
  { key: '{total_tax_included_line}', label: 'Tổng thuế đã bao gồm trong sản phẩm', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{account_name}', label: 'Người tạo', group: 'Thông tin khác' },
  { key: '{assigned_employee}', label: 'Nhân viên được gán', group: 'Thông tin khác' },
  { key: '{bin_location}', label: 'Vị trí kho', group: 'Thông tin khác' },
  { key: '{cod}', label: 'Tiền thu hộ (COD)', group: 'Thông tin khác' },
  { key: '{fulfillment_code}', label: 'Mã giao hàng', group: 'Thông tin khác' },
  { key: '{packing_note}', label: 'Ghi chú đóng gói', group: 'Thông tin đóng gói' },
];

