import { TemplateVariable } from '../types';

export const PHIEU_CHUYEN_HANG_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_fax}', label: 'Số Fax', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  // Thông tin phiếu chuyển hàng
  { key: '{order_code}', label: 'Mã phiếu', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{modified_on}', label: 'Ngày cập nhật', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{shipped_on}', label: 'Ngày chuyển', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{modified_on_time}', label: 'Thời gian cập nhật', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{shipped_on_time}', label: 'Thời gian chuyển', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{source_location_name}', label: 'Tên chi nhánh chuyển', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{source_location_address}', label: 'Địa chỉ chi nhánh chuyển', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{reference}', label: 'Tham chiếu', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{account_name}', label: 'Người tạo', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{weight_g}', label: 'Tổng khối lượng chuyển hàng (g)', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{note}', label: 'Ghi chú', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{received_on}', label: 'Ngày nhận', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{created_on_time}', label: 'Thời gian tạo', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{received_on_time}', label: 'Thời gian nhận', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{destination_location_name}', label: 'Tên chi nhánh nhận', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{destination_location_address}', label: 'Địa chỉ chi nhánh nhận', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{status}', label: 'Trạng thái', group: 'Thông tin phiếu chuyển hàng' },
  { key: '{weight_kg}', label: 'Tổng khối lượng chuyển hàng (kg)', group: 'Thông tin phiếu chuyển hàng' },
  // Thông tin sản phẩm
  { key: '{line_stt}', label: 'STT', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_code}', label: 'Mã phiên bản sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_options}', label: 'Thuộc tính sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_brand}', label: 'Thương hiệu sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_unit}', label: 'Đơn vị tính', group: 'Thông tin sản phẩm' },
  { key: '{line_price}', label: 'Đơn giá', group: 'Thông tin sản phẩm' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Thông tin sản phẩm' },
  { key: '{line_weight_g}', label: 'Tổng khối lượng sản phẩm (g)', group: 'Thông tin sản phẩm' },
  { key: '{line_product_name}', label: 'Tên sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_name}', label: 'Tên phiên bản sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_barcode}', label: 'Mã Barcode', group: 'Thông tin sản phẩm' },
  { key: '{line_category}', label: 'Loại sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{serials}', label: 'Serial', group: 'Thông tin sản phẩm' },
  { key: '{lots_number_code1}', label: 'Mã lô sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{lots_number_code2}', label: 'Mã lô - Số lượng bán sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{lots_number_code3}', label: 'Mã lô - NSX - NHH sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{lots_number_code4}', label: 'Mã lô - NSX - NHH - Số lượng bán sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_variant_image}', label: 'Ảnh phiên bản sản phẩm', group: 'Thông tin sản phẩm' },
  { key: '{line_weight_kg}', label: 'Tổng khối lượng sản phẩm (kg)', group: 'Thông tin sản phẩm' },
  // Thông tin giỏ hàng
  { key: '{receipt_quantity}', label: 'Số lượng nhận', group: 'Thông tin giỏ hàng' },
  { key: '{change_quantity}', label: 'Số lượng chênh lệch', group: 'Thông tin giỏ hàng' },
  { key: '{line_amount_received}', label: 'Thành tiền nhận', group: 'Thông tin giỏ hàng' },
  // Tổng giá trị
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total_amount_transfer}', label: 'Tổng giá trị chuyển', group: 'Tổng giá trị' },
  { key: '{total_fee_amount}', label: 'Tổng chi phí chuyển hàng', group: 'Tổng giá trị' },
  { key: '{total_receipt_quantity}', label: 'Tổng số lượng nhận', group: 'Tổng giá trị' },
  { key: '{total_amount_receipt}', label: 'Tổng giá trị nhận', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{line_variant}', label: 'Phiên bản sản phẩm', group: 'Chi tiết sản phẩm' },
  { key: '{target_location_name}', label: 'Chi nhánh nhận', group: 'Thông tin khác' },
  { key: '{transfer_code}', label: 'Mã phiếu chuyển kho', group: 'Thông tin chuyển kho' },
];

