import { TemplateVariable } from '../types';

export const PHIEU_TRA_HANG_NCC_VARIABLES: TemplateVariable[] = [
  // Thông tin cửa hàng
  { key: '{store_logo}', label: 'Logo cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_address}', label: 'Địa chỉ cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_email}', label: 'Email cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{location_name}', label: 'Tên chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{location_address}', label: 'Địa chỉ chi nhánh', group: 'Thông tin cửa hàng' },
  { key: '{store_name}', label: 'Tên cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_phone_number}', label: 'SĐT cửa hàng', group: 'Thông tin cửa hàng' },
  { key: '{store_province}', label: 'Tỉnh thành (cửa hàng)', group: 'Thông tin cửa hàng' },
  { key: '{location_province}', label: 'Tỉnh thành (chi nhánh)', group: 'Thông tin cửa hàng' },
  { key: '{print_date}', label: 'Ngày in', group: 'Thông tin cửa hàng' },
  { key: '{print_time}', label: 'Giờ in', group: 'Thông tin cửa hàng' },
  // Thông tin hoàn trả
  { key: '{supplier_name}', label: 'Tên nhà cung cấp', group: 'Thông tin hoàn trả' },
  { key: '{supplier_code}', label: 'Mã nhà cung cấp', group: 'Thông tin hoàn trả' },
  { key: '{supplier_address1}', label: 'Địa chỉ nhà cung cấp', group: 'Thông tin hoàn trả' },
  { key: '{account_name}', label: 'Tên nhân viên tạo', group: 'Thông tin hoàn trả' },
  { key: '{created_on}', label: 'Ngày tạo', group: 'Thông tin hoàn trả' },
  { key: '{note}', label: 'Lý do hoàn trả', group: 'Thông tin hoàn trả' },
  { key: '{supplier_phone_number}', label: 'SĐT nhà cung cấp', group: 'Thông tin hoàn trả' },
  { key: '{purchase_order_code}', label: 'Mã đơn nhập hàng', group: 'Thông tin hoàn trả' },
  { key: '{refund_code}', label: 'Mã phiếu hoàn trả', group: 'Thông tin hoàn trả' },
  { key: '{modified_on}', label: 'Ngày cập nhật', group: 'Thông tin hoàn trả' },
  { key: '{reference}', label: 'Tham chiếu', group: 'Thông tin hoàn trả' },
  // Thông tin giỏ hàng
  { key: '{line_stt}', label: 'STT', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_sku}', label: 'Mã SKU', group: 'Thông tin giỏ hàng' },
  { key: '{line_unit}', label: 'Đơn vị tính', group: 'Thông tin giỏ hàng' },
  { key: '{line_quantity}', label: 'Số lượng sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_price}', label: 'Giá bán', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_rate}', label: 'Chiết khấu sản phẩm %', group: 'Thông tin giỏ hàng' },
  { key: '{line_price_after_discount}', label: 'Giá sau chiết khấu trên 1 sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{tax_lines_rate}', label: 'Mức thuế sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code2}', label: 'Mã lô - Số lượng trả', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code4}', label: 'Mã lô - NSX - NHH - Số lượng trả', group: 'Thông tin giỏ hàng' },
  { key: '{line_product_name}', label: 'Tên hàng', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_name}', label: 'Tên phiên bản', group: 'Thông tin giỏ hàng' },
  { key: '{line_variant_barcode}', label: 'Mã Barcode', group: 'Thông tin giỏ hàng' },
  { key: '{line_amount}', label: 'Thành tiền', group: 'Thông tin giỏ hàng' },
  { key: '{serials}', label: 'Serial', group: 'Thông tin giỏ hàng' },
  { key: '{line_discount_amount}', label: 'Chiết khấu sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{line_amount_none_discount}', label: 'Tiền hàng (Giá * SL)', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code1}', label: 'Mã lô sản phẩm', group: 'Thông tin giỏ hàng' },
  { key: '{lots_number_code3}', label: 'Mã lô - NSX - NHH sản phẩm', group: 'Thông tin giỏ hàng' },
  // Tổng giá trị
  { key: '{total_quantity}', label: 'Tổng số lượng', group: 'Tổng giá trị' },
  { key: '{total_amount}', label: 'Giá trị hàng trả', group: 'Tổng giá trị' },
  { key: '{total_tax}', label: 'Tổng thuế', group: 'Tổng giá trị' },
  { key: '{total_landed_costs}', label: 'Chi phí hoàn lại', group: 'Tổng giá trị' },
  { key: '{transaction_refund_method_name}', label: 'Tên PTTT', group: 'Tổng giá trị' },
  { key: '{total_discounts}', label: 'Chiết khấu đơn', group: 'Tổng giá trị' },
  { key: '{total_price}', label: 'Tổng giá trị hàng trả', group: 'Tổng giá trị' },
  { key: '{discrepancy_price}', label: 'Tổng giá trị hàng trả điều chỉnh', group: 'Tổng giá trị' },
  { key: '{discrepancy_reason}', label: 'Lý do giảm trừ', group: 'Tổng giá trị' },
  { key: '{transaction_refund_amount}', label: 'Tổng tiền NCC hoàn lại', group: 'Tổng giá trị' },
  { key: '{transaction_refund_method_amount}', label: 'Giá trị PTTT', group: 'Tổng giá trị' },

  // === TỰ ĐỘNG THÊM TỪ TEMPLATE ===
  { key: '{line_total}', label: 'Thành tiền', group: 'Chi tiết sản phẩm' },
  { key: '{line_variant_code}', label: 'Mã phiên bản', group: 'Chi tiết sản phẩm' },
  { key: '{line_variant}', label: 'Phiên bản sản phẩm', group: 'Chi tiết sản phẩm' },
  { key: '{reason_return}', label: 'Lý do trả hàng', group: 'Thông tin trả hàng' },
  { key: '{refunded}', label: 'Đã hoàn tiền', group: 'Thông tin hoàn tiền' },
  { key: '{remaining}', label: 'Còn lại', group: 'Thông tin khác' },
  { key: '{return_supplier_code}', label: 'Mã phiếu trả NCC', group: 'Thông tin nhà cung cấp' },
  { key: '{supplier_address}', label: 'Địa chỉ NCC', group: 'Thông tin nhà cung cấp' },
  { key: '{supplier_email}', label: 'Email NCC', group: 'Thông tin nhà cung cấp' },
  { key: '{total_order}', label: 'Tổng đơn hàng', group: 'Tổng kết' },
];

