import { z } from 'zod'

const productSchema = z.object({
  name: z.string(),
  weight: z.number(),
  quantity: z.number(),
  product_code: z.string().optional(),
})

export const submitOrderSchema = z.object({
  apiToken: z.string().min(1),
  partnerCode: z.string().optional(),
  products: z.array(productSchema).optional(),
  id: z.string().optional(),
  pick_address_id: z.string().optional(),
  pick_name: z.string().optional(),
  pick_address: z.string().optional(),
  pick_province: z.string().optional(),
  pick_district: z.string().optional(),
  pick_ward: z.string().optional(),
  pick_street: z.string().optional(),
  pick_tel: z.string().optional(),
  tel: z.string().optional(),
  name: z.string().optional(),
  address: z.string().optional(),
  province: z.string().optional(),
  district: z.string().optional(),
  ward: z.string().optional(),
  street: z.string().optional(),
  hamlet: z.string().optional(),
  is_freeship: z.number().optional(),
  pick_money: z.number().optional(),
  value: z.number().optional(),
  not_delivered_fee: z.number().optional(),
  note: z.string().optional(),
  total_weight: z.number().optional(),
  total_box: z.number().optional(),
  transport: z.string().optional(),
  pick_option: z.string().optional(),
  pick_session: z.number().optional(),
  pick_date: z.string().optional(),
  deliver_date: z.string().optional(),
  pick_work_shift: z.number().optional(),
  deliver_work_shift: z.number().optional(),
  tags: z.array(z.number()).optional(),
  return_name: z.string().optional(),
  return_address: z.string().optional(),
  return_province: z.string().optional(),
  return_district: z.string().optional(),
  return_ward: z.string().optional(),
  return_tel: z.string().optional(),
}).passthrough()

export type SubmitOrderInput = z.infer<typeof submitOrderSchema>
